var y="function"==typeof Object.defineProperties?Object.defineProperty:function(m,v,w){if(m==Array.prototype||m==Object.prototype)return m;m[v]=w.value;return m};function aa(m){m=["object"==typeof globalThis&&globalThis,m,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var v=0;v<m.length;++v){var w=m[v];if(w&&w.Math==Math)return w}throw Error("Cannot find global object");}var ba=aa(this);
function A(m,v){if(v)a:{var w=ba;m=m.split(".");for(var u=0;u<m.length-1;u++){var z=m[u];if(!(z in w))break a;w=w[z]}m=m[m.length-1];u=w[m];v=v(u);v!=u&&null!=v&&y(w,m,{configurable:!0,writable:!0,value:v})}}function N(m){m=Math.trunc(m)||0;0>m&&(m+=this.length);if(!(0>m||m>=this.length))return this[m]}A("Array.prototype.at",function(m){return m?m:N});function Z(m){return m?m:N}A("Int8Array.prototype.at",Z);A("Uint8Array.prototype.at",Z);A("Uint8ClampedArray.prototype.at",Z);
A("Int16Array.prototype.at",Z);A("Uint16Array.prototype.at",Z);A("Int32Array.prototype.at",Z);A("Uint32Array.prototype.at",Z);A("Float32Array.prototype.at",Z);A("Float64Array.prototype.at",Z);A("String.prototype.at",function(m){return m?m:N});
(()=>{function m(a,b,c="source-atop"){let d=r(a.width,a.height),e=d.getContext("2d");return e.drawImage(a,0,0),e.globalCompositeOperation=c,e.fillStyle=b,e.fillRect(0,0,d.width,d.height),d}function v(a,b){let c=r(a.width+b.width,a.height+b.height),d=c.getContext("2d");return d.drawImage(a,0,0),d.drawImage(a,a.width,b.height),d.drawImage(b,a.width,0),d.drawImage(b,0,a.height),c}function w(a,b,c=0){0==c&&(c=b);var d=r(a.width*c,a.height*b),e=d.getContext("2d");for(let f=0;f<b;f++)for(let g=0;g<c;g++)e.drawImage(a,
g*a.width,f*a.height);return d}function u(a,b){let c=r(a.width,a.height),d=c.getContext("2d");return d.globalAlpha=b,d.drawImage(a,0,0),d.globalAlpha=1,c}function z(a,b,c,d=!1){var e=r(b,c),f=e.getContext("2d");return d&&f.fillRect(0,0,b,c),f.drawImage(a,b/2-a.width/2,c/2-a.height/2),e}function I(a){return 1E9<a?parseInt(a/1E6)+"B":1E6<a?parseInt(a/1E6)+"M":1E3<a?parseInt(a/1E3)+"K":a}function p(a,b,c,d){let e=V("#spriteSheetMain");a=O(e,8*a,8*b,8*c,8*d);return P(a,f=>"#ffffff"===f?"":f)}class ca{constructor(a=
1/30,b,c=!1){this.at=0;this.Da=null;this.Va=a;this.t=b;c&&this.start();this.p=this.Ga=!1}lc(a){if(this.Da)for(this.at+=(a-this.Da)/1E3,1<this.at&&(this.at=1);this.at>this.Va;){this.t.update(Math.floor(a/1E3));this.at-=this.Va;break}this.Da=a;this.Ga||this.mb()}mb(){requestAnimationFrame(a=>{this.lc(a)})}start(){this.Ga=!1;this.mb()}stop(){this.Ga=!0}}class Q{constructor(a){this.s=a;this.ia=[]}update(a){this.time=a;[...this.ia].forEach(b=>{b.update&&b.update(a)});this.ia=this.ia.filter(b=>!b.delete)}o(a){a.clearRect(0,
0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);[...this.ia].forEach(b=>{b.o&&b.o(a)})}notify(a){let b=a.name;a=a.event;"keydown"==b&&this.qa?this.qa(a):"keyup"==b&&this.$?this.$(a):"mousemove"==b&&this.cc||("click"==b&&this.click?this.click(a):"control"==b&&this.control?this.control(a.key):"controlts"==b&&this.zb?this.zb(a.key):"controlte"==b&&this.yb?this.yb(a.key):console.log(b))}cc(){}$(a){this.control(a.key)}}const da=Math.PI,V=(a,b=document)=>
b.querySelector(a),R=(a=1,b=0)=>0|((c=1,d=0)=>d+(c-d)*Math.random())(a,b),r=(a=0,b=0)=>{let c=document.createElement("canvas");return c.width=a,c.height=b,c},K=(a,b,c=!0)=>((d,e,f=!0)=>{var g,k,n,t;f&&0!=e%(Math.PI/4)?(n=d.width,t=d.height,g=k=Math.sqrt(n*n+t*t)):(g=d.width,k=d.height);f=r(g,k);n=f.getContext("2d");g/=2;k/=2;return n.imageSmoothingQuality="high",n.save(),n.translate(g,k),n.rotate(e),n.drawImage(d,0,0,d.width,d.height,-d.width/2,-d.height/2,d.width,d.height),n.restore(),f})(a,(b%=
8)*da/4,c),O=(a,b,c,d,e)=>{let f=r(d,e);return f.getContext("2d").drawImage(a,b,c,d,e,0,0,d,e),f},l=(a,b=1,c=null)=>{let d=a.length,e=Math.max(...a.map(n=>n.length));var f=r(e*b,d*b),g=f.getContext("2d");for(let n=0;n<d;n++)for(let t=0;t<e;t++){var k=a[n][t];c&&(k=c(k));k&&""!=k&&(g.fillStyle=k,g.fillRect(t*b,n*b,b,b))}return f},P=(a,b)=>{for(var c=a.getContext("2d").getImageData(0,0,a.width,a.height).data,d=[],e=0;e<c.length;e+=4){var f=d,g=f.push;var k=c[e];var n=c[e+1],t=c[e+2];k=0==k+n+t+c[e+
3]?null:0==k+n+t||255<k||255<n||255<t?"#000000":"#"+((k<<16)+(n<<8)+t).toString(16).padStart(6,"0");g.call(f,k)}c=[];for(e=0;e<a.height;e++)c[e]=[];f=e=0;for(g=0;g<d.length;g++)e>=a.width&&(f++,e=0),c[f][e]=d[g],b&&(c[f][e]=b(c[f][e])),e++;return c},x=(a,b,c="source-atop")=>{let d=r(a.width,a.height),e=d.getContext("2d");e.drawImage(a,0,0);e.globalCompositeOperation=c;for(c=0;c<a.width/b.width;c++)for(let f=0;f<a.height/b.height;f++)e.drawImage(b,c*b.width,f*b.height);return d},W=(a,b=!0)=>{let c=
r(a.width,a.height),d=c.getContext("2d");return d.save(),b?(d.scale(-1,1),d.drawImage(a,0,0,-1*a.width,a.height)):(d.scale(1,-1),d.drawImage(a,0,0,a.width,-1*a.height)),d.restore(),c},F=a=>{var b=r(a[0].width,a[0].height),c=b.getContext("2d");for(let d in a)c.drawImage(a[d],0,0);return b};class B{constructor(){}static get(a,b,c,d,e="Arial",f=0,g=0){let k=r(1,1).getContext("2d");k.font=b+"px "+e;f=r(parseInt(f||k.measureText(a).width||1),g||b+2);k=f.getContext("2d");k.font=b+"px "+e;k.fillStyle=c;
k.fillText(a,0,b-2);d&&(f=x(f,d));a=r(f.width,f.height);b=a.getContext("2d");return b.fillStyle="#ffffff",b.drawImage(f,0,0),a}}const h={W:p(0,0,1,1),Z:p(1,0,1,1),U:p(2,0,1,1),ha:p(3,0,1,1),ta:p(4,0,1,1),rb:p(0,1,1,1),B:p(1,1,1,1),Pa:p(2,1,1,1),ra:p(3,1,1,1),sb:p(4,1,1,1),Ta:p(0,2,1,1),wb:p(1,2,1,1),Ub:p(2,2,1,1),nb:p(0,3,1,1),tb:p(1,3,2,1),ka:p(9,0,4,4),va:p(3,2,2,2),h:p(0,4,2,2),jb:p(2,4,2,2),kb:p(4,4,1,2),fc:p(5,4,1,2),nc:p(6,4,1,2),Qa:p(7,4,2,2),Ua:p(9,4,2,2),Aa:p(5,0,2,2),Ha:p(5,2,2,2),cb:p(7,
0,2,2),bb:p(7,2,2,2),direction:p(11,4,2,2),ac:p(0,6,2,2),Wb:p(2,6,2,2),Xb:p(4,6,2,2),Yb:p(6,6,2,2),Zb:p(8,6,2,2),$b:p(10,6,2,2)};var C=l(h.W,1),D=l(h.Z,1),G=l(h.U,1),E=l(h.ha,1),S=l(h.ta,1);l(h.rb,1);l(h.B,1);l(h.Pa,1);var T=l(h.ra,1);l(h.sb,1);l(h.Ta,1);l(h.wb,1);l(h.Ub,1);l(h.nb,1);l(h.tb,1);l(h.ka,1);l(h.va,1);var ea=l(h.h,1);l(h.jb,1);l(h.kb,1);l(h.fc,1);l(h.nc,1);l(h.Qa,1);l(h.Ua,1);l(h.Aa,1);l(h.Ha,1);l(h.cb,1);l(h.bb,1);l(h.direction,1);var U=l(h.ac,1),fa=l(h.Wb,1),ha=l(h.Xb,1),X=l(h.Yb,1),
ia=l(h.Zb,1),ja=l(h.$b,1);l(h.ka,2);l(h.Aa,2);l(h.Ha,2);l(h.va,2);class ka{constructor(a,b=2){this.i=a;a=l(h.ka,b);b=P(a);var c=b.flat(),d=[...(new Set(c))];c={};for(f of d)for(c[f]=[],d=0;d<b.length;d++){c[f].push([]);for(var e=0;e<b[d].length;e++)b[d][e]===f?c[f][d][e]="#000000":c[f][d][e]=null}var f=(delete c.qc,c);var g=l(f["#6a6a6a"]),k=l(f["#c2c2c2"]);f=x(g,u(C,.5));b=x(g,u(D,.5));c=x(g,u(G,.5));d=x(g,u(S,.5));e=x(g,u(E,.5));g=x(g,u(T,.5));var n=x(k,u(C,.2)),t=x(k,u(D,.2)),la=x(k,u(G,.2)),ma=
x(k,u(S,.2)),na=x(k,u(E,.2));k=x(k,u(T,.2));this.W=F([a,n,f]);this.Z=F([a,t,b]);this.U=F([a,la,c]);this.ta=F([a,ma,d]);this.ha=F([a,na,e]);this.ra=F([a,k,g])}update(a){this.time=a}}class oa extends Q{constructor(a){super(a);a=v(C,D);var b=v(E,C);this.V=new ka(this);this.h=l(h.h,2);this.za=function(c,d,e,f,g=1){1<g&&(c=w(c,g),d=w(d,g));c=v(c,d);d=r(c.width*f,c.height*e);g=d.getContext("2d");for(let k=0;k<e;k++)for(let n=0;n<f;n++)g.drawImage(c,k*c.height,n*c.width);return d}(a,b,this.s.canvas.width/
8,this.s.canvas.height/8);this.za=u(this.za,.2);this.log=this.Mb();this.buffer=this.xa();this.aa=-20;this.Ba=this.Lb()}Mb(){var a=r(400,200),b=a.getContext("2d"),c=v(C,D),d=v(E,E),e=v(D,G),f=v(G,C);return this.P=[B.get("13th CENTURY\u2122",20,"green",f,"Arial Black"),B.get("ROBIN\u27b8HOOD ",40,"green",c,"Arial Black"),B.get("THE\u27b8OUTLAW ",28,"green",d,"Arial Black"),B.get("\u26051370s\u2235\u2234\u2235\u2234\u2235\u2234\u2235\u2234\u2235\u2234\u2235\u2234\u22352023\u2605",15,"green",e,"Arial Black")],
b.drawImage(m(this.P[0],"white"),0,1),b.drawImage(this.P[0],1,1),b.drawImage(m(this.P[1],"red"),1,18),b.drawImage(this.P[1],0,17),b.drawImage(m(this.P[2],"white"),85,53),b.drawImage(this.P[2],85,52),b.drawImage(this.P[3],82,82),a}Lb(){var a="you step into the legendary shoes of Robin Hood.;your mission is to make the world a better place.;- explore forest and hunt animals;- do quests and trade with merchants;- spread the wealth to the poor;- improve your stats and defend the village;a w s d / arrows for movement;e interact, q menue, space fire;explore forest hunt animal;trade with merchants;- give goodies to villagers for free (gain morale);- take quests from villagers for extra love;find old wizzard for a magic bow;more instructions can be learned in game".split(";"),
b=r(360,500);let c=b.getContext("2d");c.fillStyle="white";c.font="16px Arial";for(let d=0;d<a.length;d++)c.fillText(a[d],0,25*d+20);return b}update(a){this.time=a;this.aa+=.8}xa(){let a=r(this.s.C.width,this.s.C.height),b=a.getContext("2d");b.drawImage(this.za,0,0);return b.drawImage(this.log,400>this.s.C.width?16:128,74),a}o(a){let b=20;a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);a.drawImage(this.buffer,0,0);a.fillStyle="green";
a.font="16px Arial";a.fillText("Time "+this.time,20,b);a.fillText("use any key to load menu ",20,b+20);a.drawImage(this.V.W,16,192);a.drawImage(this.V.Z,88,192);a.drawImage(this.V.U,160,192);a.drawImage(this.V.ta,232,192);a.drawImage(this.V.ha,304,192);a.drawImage(this.V.ra,376,192);a.drawImage(this.h,16,320);a.drawImage(O(this.Ba,0,this.aa%this.Ba.height,this.Ba.width,200),64,320)}oa(){100<this.aa&&this.s.Ja();this.aa=100}control(){this.oa()}click(){this.oa()}qa(){this.oa()}$(){this.oa()}}class pa{constructor(a,
b=300,c=!0,d=!0,e=3){this.I=a;this.ic=b;this.loop=e;this.pitch=d;this.da=!1;this.K=new AudioContext;this.eb=this.I;c&&this.start()}toggle(){this.da?this.stop():this.start()}start(){this.da=!0;this.ib()}stop(){this.da=!1}reset(){this.I=this.eb}Ob(a){switch(a){case "B":return 493.88;case "C":return 261.63;case "D":return 293.66;case "E":return 329.63;case "F":return 349.23;case "G":return 392}return 440}Jb(a){var b=this.Ob(a[0]);return 1<a.length?b*Math.pow(2,a[1]/12):b}ib(){if(this.da)if(0===this.I.length&&
0<this.loop&&(this.I=this.eb,this.loop--),0===this.I.length)this.stop();else{var a=this.I[0];this.pitch?(this.I[1],this.I=this.I.slice(2)):this.I=this.I.slice(1);var b=this.K.createOscillator(),c=this.K.createGain();b.connect(c);c.connect(this.K.destination);b.frequency.setValueAtTime(this.Jb(a),this.K.currentTime);b.start();c.gain.setValueAtTime(0,this.K.currentTime);c.gain.exponentialRampToValueAtTime(.05,this.K.currentTime+.02);setTimeout(()=>{c.gain.setValueAtTime(.05,this.K.currentTime);c.gain.exponentialRampToValueAtTime(.001,
this.K.currentTime+.02);b.stop(this.K.currentTime+.02);this.ib()},60/this.ic*1E3)}}}class qa extends Q{constructor(a){super(a);this.u={ha:E,U:G,Z:D,W:C,ra:T,h:ea};a=400>this.s.C.width?32:100;this.v=[{x:a,y:128},{x:a,y:160},{x:a,y:192},{x:a,y:224},{x:a,y:256}];this.ca="robin hood";this.F=0;this.ga=!1;this.buffer=this.hc()}hc(){var a=r(this.s.C.width,this.s.C.height);return a.getContext("2d"),a}update(a){this.time=a}o(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,
0,a.canvas.width,a.canvas.height);a.fillStyle="green";a.font="16px Arial";a.drawImage(this.buffer,0,0);a.drawImage(B.get("\u2588 \u24c5\u24c1\u24b6\u24ce \u24bc\u24b6\u24c2\u24ba",24,"green",this.u.Z,"Verdana"),this.v[0].x+20,this.v[0].y);a.drawImage(B.get("\u2588 SOUND : "+(this.ga&&1==this.ga?"on":"off"),24,"green",this.u.U,"Verdana"),this.v[1].x+20,this.v[1].y);a.drawImage(B.get("\u2588 Music : "+(this.X&&this.X.da?"on":"off"),24,"green",this.u.U,"Verdana"),this.v[2].x+20,this.v[2].y);a.drawImage(B.get(`\u2588 NAME : ${this.ca}`,
24,"green",this.u.U,"Verdana"),this.v[3].x+20,this.v[3].y);a.drawImage(B.get("\u2588 STATS \u32e1",24,"green",this.u.W,"Roboto"),this.v[4].x+20,this.v[4].y);a.drawImage(this.u.h,this.v[this.F].x,this.v[this.F].y+4);a.fillText("Time "+this.time,20,20)}click(){}control(a){if("s"===a||"ArrowDown"===a)a=this.F+1,this.F=(0>a?-a:a)%this.v.length;else if("w"===a||"ArrowUp"===a)a=this.F-1,this.F=(0>a?-a:a)%this.v.length;else if("a"===a||"ArrowLeft"===a||"d"===a||"ArrowRight"===a||"space"===a||" "===a)0==
this.F?this.s.jc():1==this.F?this.ga?this.ga=!1:this.ga=!0:2==this.F?(this.X||(this.X=new pa("E4E4D4E4E4D4E4G4G4A4A4E4E4D4E4E4D4E4G4G4A4A4G4G4E4E4D4E4E4D4E4A4A4",120,!1,!0,2E3)),this.X.toggle()):3==this.F?this.ca=(a=prompt("name",this.ca))&&0<a.length?a.substring(0,10):this.ca:4==this.F&&(this.X&&this.X.stop(),alert("under construction"))}qa(){}$(a){this.control(a.key)}}class q{constructor(a,b){this.x=a;this.y=b}is(a){let b=this.y,c=a.y;return this.x==a.x&&b==c}L(a){if(!a)return 1/0;let b=this.x,
c=this.y,d=a.x;a=a.y;if(b==d&&c==a)return 0;if(b==d)return Math.abs(c-a);if(c==a)return Math.abs(b-d);let e=0;return e+=Math.pow(b-d,2),e+=Math.pow(c-a,2),e=Math.sqrt(e),e}na(a){let b=this.x,c=this.y,d=a.x;a=a.y;return b==d&&c==a?4:b>d?6:b<d?2:c<a?4:c>a?0:4}$a(a,b){let c=this.clone();return c.move(a,b),c}move(a,b){0==a?this.y-=b:4==a?this.y+=b:6==a?this.x-=b:2==a?this.x+=b:7==a?(this.y-=b,this.x-=b):1==a?(this.y-=b,this.x+=b):3==a?(this.y+=b,this.x+=b):5==a&&(this.y+=b,this.x-=b)}$a(a,b){let c=this.clone();
return c.move(a,b),c}dc(a,b){let c=a.x-this.x,d=a.y-this.y,e=Math.sqrt(c*c+d*d);e<b?(this.x=a.x,this.y=a.y):(this.x+=(c/e||0)*b,this.y+=(d/e||0)*b)}clone(){return new q(this.x,this.y)}o(a,b="red"){a.fillStyle=b;this.wa(a,3,b)}wa(a,b=4,c="green"){a.fillStyle=c;a.strokeStyle=c;a.beginPath();a.arc(this.x,this.y,b,0,2*Math.PI);a.fill()}static wa(a,b,c,d=1,e="green"){a.fillStyle=e;a.strokeStyle=e;a.beginPath();a.arc(b,c,d,0,2*Math.PI);a.fill()}}const L=[{T:15,attack:1,j:1,name:"rabbit"},{T:50,attack:4,
j:5,name:"wolf"},{T:50,attack:10,j:8,name:"deer"},{T:50,attack:20,j:10,name:"bear"},{T:10,attack:15,j:10,name:"npcman"},{T:10,attack:10,j:10,name:"npcgirl"}];class H{constructor(a,b=0,c=null){this.type=b;this.i=a;this.u=this.Y();this.l=this.u[this.type];this.g=c||a.Db();this.j=L[this.type].j;this.ba=L[this.type].j;this.Fa=L[this.type].T}Pb(){var a=[],b=this.i.m;let c=this.g.x/b,d=this.g.y/b;if(this.i.N(c+1,d)&&a.push(new q),this.i.N(c+1,d)&&a.push(new q(c*b+b,d*b)),this.i.N(c-1,d)&&a.push(new q(c*
b-b,d*b)),this.i.N(c,d+1)&&a.push(new q(c*b,d*b+b)),this.i.N(c,d-1)&&a.push(new q(c*b,d*b-b)),0<a.length)a=a[R(0,a.length)],this.g=new q(a.x,a.y)}update(a){this.time=a;this.Fa--;0>=this.Fa&&(this.Fa=L[this.type].T,this.Pb(),this.g.L(this.i.h.g)<2*this.i.m&&(this.i.h.j-=this.type+1,this.i.h.qb=10))}ya(){var a=r(this.l.width,3),b=a.getContext("2d");b.fillStyle="green";return b.fillRect(0,0,this.j/this.ba*this.l.width,3),a}o(a){a.drawImage(this.l,this.g.x,this.g.y);a.drawImage(this.ya(),this.g.x,this.g.y)}Y(){if(H.O)return H.O;
var a=this.i.M,b=this.i.m,c=z(l(h.nb,a),b,b,!1),d=z(l(h.tb,a),b,b,!1),e=z(l(h.Ua,a),b,b,!1),f=l(h.Qa,a),g=l(h.cb,a),k=l(h.bb,a);a=l(h.rb,a);this.H=this.w=b;return H.O=[c,d,e,f,g,k,a],H.O}}class ra extends H{constructor(a,b=0,c=null){super(a,b,c)}o(a){super.o(a);a.drawImage(this.u[6],this.g.x+.65*this.l.width,this.g.y+.25*this.l.height)}}const sa=[{n:"tree",D:1,c:"#0d3702"},{n:"brick",D:1,c:"#bf0a0a"},{n:"dirt",D:0,c:"#d9a066"},{n:"grass",D:0,c:"#99e550"},{n:"water",D:2,c:"#8a99f6"},{n:"steel",D:1,
c:"#6a6a6a"},{n:"player",D:0,c:"#130c40"},{n:"army",D:0,c:"#ff0000"},{n:"cave",D:1,c:"#2e2b2b"},{n:"deerspawnpoint",D:0,c:"#df7126"},{n:"rabbitspawnpoint",D:0,c:"#d1d1d1"},{n:"wolfspawnpoint",D:0,c:"#898898"}];class ta{constructor(a,b=1){this.S=a;this.R=[];this.lb=[];this.Sa=[];this.Ab=[];this.Ya=[];this.pb=[];console.log(h);console.log(h.W);console.log(h.ha);console.log(C);this.Qb(b)}Ca(a,b){return(a=Math.floor(a),b=Math.floor(b),0>a)||a>this.R.length-1||0>b||b>this.R.length-1||!this.R[a]?!0:this.Tb(this.R[b][a])}Tb(a){var b=
sa.find(c=>c.c==a);return null==b?1:b.D}Nb(){var a=U.width,b=r(4*a,4*U.height),c=b.getContext("2d");for(let d=0;4>d;d++)for(let e=0;4>e;e++)c.drawImage(ha,d*a,e*a);return c.drawImage(X,a,0),c.drawImage(X,3*a,3*a),c.drawImage(ia,2*a,3*a),c.drawImage(ja,2*a,a),c.drawImage(fa,0,0),c.drawImage(U,a,a),b}Qb(a=1){var b=this.Nb();this.map=b;this.R=b=P(b);var c={"#d9a066":w(C,2*a),"#bf0a0a":w(S,2*a),"#99e550":w(D,2*a),"#8a99f6":w(G,2*a),"#6a6a6a":w(E,2*a),"#0d3702":l(h.sb,2*a),"#a9a9a9":l(h.ka,2*a),"#fbf236":l(h.Aa,
2*a),"#eca732":l(h.Ha,2*a),"#2e2b2b":l(h.va,2*a)};a*=16;for(var d=r(b.length*a,b.length*a),e=d.getContext("2d"),f=0;f<b.length;f++)for(var g=0;g<b[f].length;g++){var k=b[g][f];e.drawImage(c["#99e550"],f*a,g*a);"#0d3702"==k?e.drawImage(c["#0d3702"],f*a,g*a):"#d9a066"==k?e.drawImage(c["#d9a066"],f*a,g*a):"#bf0a0a"==k?e.drawImage(c["#bf0a0a"],f*a,g*a):"#99e550"==k?e.drawImage(c["#99e550"],f*a,g*a):"#df7126"==k?(e.drawImage(c["#99e550"],f*a,g*a),this.Ab.push([f,g])):"#8a99f6"==k?e.drawImage(c["#8a99f6"],
f*a,g*a):"#6a6a6a"==k?e.drawImage(c["#6a6a6a"],f*a,g*a):"#a9a9a9"==k?this.Ra=new q(f*a,g*a):"#2e2b2b"==k?this.Sa.push(new q(f*a,g*a)):"#fbf236"==k?this.Ya.push(new q(f*a,g*a)):"#eca732"==k?this.pb.push(new q(f*a,g*a)):"#130c40"==k?(this.Na=new q(f*a,g*a),b[f][g]="#d9a066"):"#ff0000"==k?this.lb.push(new ra(this.S,4,new q(f*this.S.m,g*this.S.m))):"#000000"==k||"#d1d1d1"==k||"#898898"==k||console.log(k,"unclassified")}e.drawImage(c["#a9a9a9"],this.Ra.x,this.Ra.y);this.Ya.forEach(n=>{e.drawImage(c["#fbf236"],
n.x,n.y)});this.pb.forEach(n=>{e.drawImage(c["#eca732"],n.x,n.y)});this.Sa.forEach(n=>{e.drawImage(c["#2e2b2b"],n.x,n.y)});this.bc=d}}class ua{constructor(a,b,c,d,e){this.Xa=a;this.g=new q(0,0);this.H=c;this.w=b;this.fb=d;this.gb=e}Gb(a){this.g=new q(a.x,a.y)}Vb(a){this.g=a}move(a){this.g.move(a,32)}Hb(a){var b=this.g.x-this.w/2,c=this.g.y-this.H/2;return O(a,0>b?0:b,0>c?0:c,this.w,this.H)}o(a,b){let c;let d,e,f,g,k,n;var t=this.g.y-this.H/2;c=this.g.x-this.w/2;0>=c&&(c=0,this.g.x=c+this.w/2);0>=
t&&(t=0,this.g.y=t+this.H/2);c+this.w>b.width&&(c=b.width-this.w,this.g.x=c+this.w/2);t+this.H>b.height&&(t=b.height-this.H,this.g.y=t+this.H/2);f=this.fb;g=this.gb;d=k=this.w;e=n=this.H;a.drawImage(b,c,t,d,e,f,g,k,n)}Kb(a,b,c=32){var d=this.g.x-this.w/2,e=this.g.y-this.H/2;a=a+(0>d?0:d)-this.fb;b=b+(0>e?0:e)-this.gb;return a=Math.floor(a/c)*c,b=Math.floor(b/c)*c,new q(a,b)}}class va{constructor(){this.ub=this.Ka=8}}class Y{constructor(a){this.g=new q(a.x,a.y);this.j=1}o(a){a.drawImage(this.l,this.g.x,
this.g.y)}}class J extends Y{constructor(a){super(a.g);this.e=a;this.direction=a.direction;this.u=this.Y();this.l=this.u[this.direction];this.width=this.l.width;this.height=this.l.height;this.speed=this.width/2;this.Bb=this.e.attributes.Ka*this.speed/10;this.ab=0;this.j=1}update(a){this.time=a;this.ab++;this.ab<this.Bb?(this.g.move(this.direction,this.speed),this.e.xb(this)):this.j=0}Y(){if(J.O)return J.O;var a=this.e.i.M,b=16*a,c=z(l(h.Pa,a),b,b);a=K(c,0);b=K(c,2);var d=K(c,4);c=K(c,6);this.w=a.width;
this.H=a.height;return J.O=[c,c,a,a,b,b,d,c],J.O}}class M extends Y{constructor(a,b,c=1){super(b);this.i=a;this.value=c;this.l=this.Ib()}update(a){this.time=a;this.g.L(this.i.h.g)<1.5*this.i.m&&(this.i.h.ua+=this.value,this.j=0)}o(a){super.o(a)}Ib(){if(M.Ma)return M.Ma;var a=this.i.m;a=z(l(h.Ta,this.i.M),a,a,!1);return M.Ma=a,a}}class wa{constructor(a){this.i=a;this.j=this.ba=100;this.ua=this.ea=0;this.attributes=new va(1);this.g=new q(0,0);this.destination=new q(0,0);this.pa=!1;this.time=0;this.direction=
4;this.u=this.Y();this.l=this.u[4];this.fa=[];this.ma=0;this.La=1E4}setPosition(a){this.g=new q(a.x,a.y);this.destination=new q(a.x,a.y)}update(a){this.ma=Math.max(this.ma-1,0);this.fa=this.fa.filter(b=>0<b.j);[...this.fa].forEach(b=>{b.update&&b.update(a)});this.time=a;0!=this.g.L(this.destination)?(this.pa=!0,this.g.dc(this.destination,this.attributes.ub),this.i.ja.Gb(this.g)):this.pa=!1}Fb(){0<this.ma||(this.ma=20-2*this.attributes.Ka,this.La--,this.fa.push(new J(this)),this.ec())}xb(a){var b=
a.g;b=this.i.J.Ca(b.x/this.i.m,b.y/this.i.m);1!=b&&1!=b||2==b||(a.j=0,this.hb());for(let c=0;c<this.i.A.length;c++)b=this.i.A[c],b.g.L(a.g)<this.i.m&&null!=b.type&&(b.j-=a.j,0>=b.j&&(this.i.A.push(new M(this.i,b.g,b.type+1)),4==b.type||5==b.type?this.ea-=b.type+1:this.ea+=b.type+1),this.hb(),a.j=0)}ya(){var a=r(this.l.width,3),b=a.getContext("2d");b.fillStyle="green";this.j<this.ba/2&&(b.fillStyle="orange");this.j<this.ba/2&&(b.fillStyle="red");return b.fillRect(0,0,this.j/this.ba*this.l.width,3),
a}o(a){a.drawImage(this.l,this.g.x,this.g.y);4==this.direction&&a.drawImage(this.B,this.g.x+this.l.width-this.B.width,this.g.y+this.l.height-1.5*this.B.height);6==this.direction&&a.drawImage(W(this.B),this.g.x+this.l.width-1.6*this.B.width,this.g.y+this.l.height-1.3*this.B.height);2==this.direction&&a.drawImage(this.B,this.g.x+this.l.width-1.2*this.B.width,this.g.y+this.l.height-1.3*this.B.height);[...this.fa].forEach(b=>{b.o&&b.o(a)});a.drawImage(this.ya(),this.g.x,this.g.y);0<this.qb&&(a.fillStyle=
"#ff0000aa",a.fillRect(this.g.x,this.g.y,this.l.width,this.l.height),this.qb--)}ob(a,b){this.direction=a=this.g.na(new q(a,b));this.l=this.u[a]}moveTo(a,b){if(!this.i.N(a,b)){var c=this.g.na(new q(a,b));this.direction=c;0!=this.g.L(new q(a,b))&&(this.l=this.u[c],this.move(c))}}move(a){a===this.direction?this.pa||this.destination.move(a,this.width):this.direction=a}Y(){this.B=l(h.B,this.i.M);var a=l(h.h,this.i.M),b=l(h.jb,this.i.M),c=l(h.kb,this.i.M);return this.width=a.width,this.height=a.height,
[b,b,c=z(c,this.width,this.height),a,a,a,W(c,!0),b]}ec(){const a=new (window.AudioContext||window.webkitAudioContext),b=a.createOscillator();b.type="sawtooth";b.frequency.setValueAtTime(500,a.currentTime);const c=a.createGain();c.gain.setValueAtTime(.2,a.currentTime);const d=a.createBiquadFilter();d.type="lowpass";d.frequency.setValueAtTime(500,a.currentTime);b.connect(c);c.connect(d);d.connect(a.destination);b.start();c.gain.exponentialRampToValueAtTime(.01,a.currentTime+.5);b.stop(a.currentTime+
1)}hb(){const a=new (window.AudioContext||window.webkitAudioContext),b=a.createOscillator();b.type="square";b.frequency.setValueAtTime(400,a.currentTime);const c=a.createGain();c.gain.setValueAtTime(.2,a.currentTime);const d=a.createBiquadFilter();d.type="lowpass";d.frequency.setValueAtTime(400,a.currentTime);b.connect(c);c.connect(d);d.connect(a.destination);b.start();c.gain.exponentialRampToValueAtTime(.01,a.currentTime+.5);b.stop(a.currentTime+1)}}class xa extends Q{constructor(a){super(a);this.Sb()}Sb(){this.M=
2;this.m=16*this.M;this.keyboard={};this.J=new ta(this,this.M);this.Ea=u(this.J.map,.7);this.h=new wa(this);this.h.setPosition(this.J.Na?this.J.Na:new q(224,224));this.ja=new ua(this,this.s.C.width,this.s.C.height,0,0);this.ja.Vb(this.h.g);this.ca="robin hood";this.A=[...this.J.lb];this.mc=this.Eb();this.Wa();for(let a=0;25>a;a++)this.vb()}Rb(a,b){a=new q(a,b);for(let c=0;c<this.A.length;c++)if(b=this.A[c],b.g.L(a)<this.m)return b;return null}N(){}N(a,b){return null!=this.Rb(a,b)||this.J.Ca(a/this.m,
b/this.m)}xa(){var a=r(this.s.C.width,this.s.C.height);let b=a.getContext("2d");b.clearRect(0,0,b.canvas.width,b.canvas.height);b.fillStyle="black";b.fillRect(0,0,b.canvas.width,b.canvas.height);var c=(e=>{if(!e)return null;let f=r(e.width,e.height);return f.getContext("2d").drawImage(e,0,0),f})(this.J.bc),d=c.getContext("2d");[...this.A].forEach(e=>{e.o&&e.o(d)});this.h.o(d);c=this.ja.Hb(c);return b.drawImage(c,0,0),a}update(a){this.time=a;[...this.A].forEach(b=>{b.update&&b.update(a)});this.A=this.A.filter(b=>
0<b.j);this.h.update(a);for(let b in this.keyboard)this.keyboard[b]&&this.Oa(b);0>=this.h.j&&(alert("game over"),this.s.S=null,this.h.j=100,this.s.Ja())}vb(){if(!(25<this.A.length)){var a=new H(this,R(0,3));this.A.push(a)}}Eb(){var a=[];for(let c=0;c<this.J.R.length;c++)for(let d=0;d<this.J.R.length;d++){var b=new q(c*this.m,d*this.m);this.J.Ca(c,d)||a.push(b)}return a}Db(){var a=this.Wa(8,25);return 0<a.length?a[R(0,a.length)]:new q(this.m,this.m)}Wa(a=8,b=13){var c=this.mc;c=(c=c.filter(f=>f.L(this.h.g)>
this.m*a)).filter(f=>f.L(this.h.g)<this.m*b);var d=[];for(let f in c){var e=!0;for(let g=0;g<this.A.length;g++)if(this.A[g].g.L(new q(c[f].x,c[f].y))<this.m){e=!1;break}e&&d.push(c[f])}return c}Oa(a){if(" "!==a&&"space"!==a||this.h.Fb()," "!==a&&"e"!==a)if("q"===a)this.keyboard.q=!1,this.s.Ja();else if(!this.h.pa){var b=this.h.g.clone(),c=!1;"s"===a||"ArrowDown"===a?(b.move(4,this.h.height),c=!0):"w"===a||"ArrowUp"===a?(b.move(0,this.h.height),c=!0):"d"===a||"ArrowRight"===a?(b.move(2,this.h.height),
c=!0):"a"!==a&&"ArrowLeft"!==a||(b.move(6,this.h.height),c=!0);c&&(this.h.g.na(b)!=this.h.direction?(this.h.ob(b.x,b.y),this.keyboard={}):this.N(b.x,b.y)?this.h.ob(b.x,b.y):this.h.moveTo(b.x,b.y))}}o(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="green";a.font="16px Arial";a.drawImage(this.xa(),0,0);a.fillStyle="#004b52d6";a.fillRect(0,0,a.canvas.width,32);a.fillStyle="#ffffff";a.fillText("\u2665 "+I(this.h.j),15,
15);a.fillText("\u2295 "+I(this.h.ea),15,30);a.fillText("\u27b9\t"+I(this.h.La),96,15);a.fillText("\u0556\t"+I(this.h.ua),96,30);a.fillText("Mobs "+I(this.A.length),320,15);a.drawImage(this.Ea,0,a.canvas.height-this.Ea.height);q.wa(a,this.h.g.x/this.m,a.canvas.height-this.Ea.height+this.h.g.y/this.m,3,"green")}click(a){a=this.ja.Kb(a.offsetX,a.offsetY,this.m);a=new q(a.x,a.y);this.h.direction=this.h.g.na(a);a=this.h.g.$a(this.h.direction,this.h.height);this.h.moveTo(a.x,a.y)}control(a){this.Oa(a)}qa(a){this.keyboard[a.key]=
!0}$(a){this.keyboard[a.key]=!1}}class ya{constructor(a){return this.target=a,this.Ia=[],!!a.addEventListener}sub(a){this.Ia.push(a)}clear(){this.Ia=[]}fireEvent(a){var b=this.Ia,c;for(c in b)b[c].notify&&b[c].notify(a)}}class za{constructor(a){this.C=a;this.la=document.querySelector(a.la);this.canvas=Object.assign(document.createElement("canvas"),{width:a.width,height:a.height,className:"gamecanvas"});this.la.appendChild(this.canvas);this.G=new ya(document);["keydown","keyup"].forEach(b=>{document.addEventListener(b,
c=>{this.G.fireEvent({name:b,event:c})})});this.canvas.addEventListener("click",b=>{this.G.fireEvent({name:"click",event:b})});this.kc();400>this.C.width&&(a.framerate/=2);this.sa=new ca(a.framerate,this,!0);this.Cb()}update(a){if(0==this.sa.p)if(this.time=a,this.i)try{this.i.update(a),this.i.o(this.canvas.getContext("2d"))}catch(b){console.log(b),this.sa.stop()}else this.sa.stop()}kc(){this.i=new oa(this);this.G.clear();this.G.sub(this.i)}Ja(){this.Za||(this.Za=new qa(this));this.i=this.Za;this.G.clear();
this.G.sub(this.i)}jc(){this.S||(this.S=new xa(this));this.i=this.S;this.G.clear();this.G.sub(this.i)}Cb(){if(!(400<this.C.width)){var a=Object.assign(document.createElement("div"),{className:"controls_container"});a.innerHTML="<table>\n        <tr><td id='q'>q</td><td id='w'>w</td><td id='e'>e</td><td class=\"padding\"></td><td id='space'>space</td> </tr>\n        <tr><td id='a'>a</td><td id='s'>s</td><td id='d'>d</td><td class=\"padding\"></td><td id='f'>f</td></tr></table>";this.la.appendChild(a);
var b=((c,d=document)=>d.querySelectorAll(c))(".controls_container td");for(let c=0;c<b.length;c++)b[c].addEventListener("click",()=>{this.G.fireEvent({name:"control",event:{key:b[c].id}})}),b[c].addEventListener("touchstart",()=>{this.G.fireEvent({name:"controlts",event:{key:b[c].id}})}),b[c].addEventListener("touchend",()=>{this.G.fireEvent({name:"controlte",event:{key:b[c].id}})})}}}const Aa={la:".canvas_container",sc:32,oc:1,framerate:1/30,width:32*parseInt(window.innerWidth/32),height:576,pc:"Assets",
rc:V("#spriteSheetMain")};class Ba extends za{constructor(a){super(a)}}document.addEventListener("DOMContentLoaded",function(){window.Xa||(window.Xa=new Ba(Aa))},!1)})();
