var Da="function"==typeof Object.defineProperties?Object.defineProperty:function(l,v,w){if(l==Array.prototype||l==Object.prototype)return l;l[v]=w.value;return l};function Ea(l){l=["object"==typeof globalThis&&globalThis,l,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var v=0;v<l.length;++v){var w=l[v];if(w&&w.Math==Math)return w}throw Error("Cannot find global object");}var Fa=Ea(this);
function B(l,v){if(v)a:{var w=Fa;l=l.split(".");for(var u=0;u<l.length-1;u++){var D=l[u];if(!(D in w))break a;w=w[D]}l=l[l.length-1];u=w[l];v=v(u);v!=u&&null!=v&&Da(w,l,{configurable:!0,writable:!0,value:v})}}function G(l){l=Math.trunc(l)||0;0>l&&(l+=this.length);if(!(0>l||l>=this.length))return this[l]}B("Array.prototype.at",function(l){return l?l:G});function Y(l){return l?l:G}B("Int8Array.prototype.at",Y);B("Uint8Array.prototype.at",Y);B("Uint8ClampedArray.prototype.at",Y);
B("Int16Array.prototype.at",Y);B("Uint16Array.prototype.at",Y);B("Int32Array.prototype.at",Y);B("Uint32Array.prototype.at",Y);B("Float32Array.prototype.at",Y);B("Float64Array.prototype.at",Y);B("String.prototype.at",function(l){return l?l:G});
(()=>{function l(a,b,c="source-atop"){let d=r(a.width,a.height),e=d.getContext("2d");return e.drawImage(a,0,0),e.globalCompositeOperation=c,e.fillStyle=b,e.fillRect(0,0,d.width,d.height),d}function v(a,b){let c=r(a.width+b.width,a.height+b.height),d=c.getContext("2d");return d.drawImage(a,0,0),d.drawImage(a,a.width,b.height),d.drawImage(b,a.width,0),d.drawImage(b,0,a.height),c}function w(a,b,c=0){0==c&&(c=b);var d=r(a.width*c,a.height*b),e=d.getContext("2d");for(let f=0;f<b;f++)for(let h=0;h<c;h++)e.drawImage(a,
h*a.width,f*a.height);return d}function u(a,b){let c=r(a.width,a.height),d=c.getContext("2d");return d.globalAlpha=b,d.drawImage(a,0,0),d.globalAlpha=1,c}function D(a,b,c,d=!1){var e=r(b,c),f=e.getContext("2d");return d&&f.fillRect(0,0,b,c),f.drawImage(a,b/2-a.width/2,c/2-a.height/2),e}function H(a){return 1E9<a?parseInt(a/1E6)+"B":1E6<a?parseInt(a/1E6)+"M":1E3<a?parseInt(a/1E3)+"K":a}function n(a,b,c,d){let e=ia("#spriteSheetMain");a=Z(e,8*a,8*b,8*c,8*d);return aa(a,f=>"#ffffff"===f?"":f)}function ja(a,
b){for(var c=0;c<a.length;c++)for(var d=0;d<a[c].length;d++)b(a[d][c],c,d)}class Ga{constructor(a=1/30,b,c=!1){this.at=0;this.ab=null;this.tb=a;this.t=b;c&&this.start();this.p=this.jb=!1}Sc(a){if(this.ab)for(this.at+=(a-this.ab)/1E3,1<this.at&&(this.at=1);this.at>this.tb;){this.t.update(Math.floor(a/1E3));this.at-=this.tb;break}this.ab=a;this.jb||this.Ib()}Ib(){requestAnimationFrame(a=>{this.Sc(a)})}start(){this.jb=!1;this.Ib()}stop(){this.jb=!0}}class P{constructor(a){this.s=a;this.Da=[]}update(a){this.time=
a;[...this.Da].forEach(b=>{b.update&&b.update(a)});this.Da=this.Da.filter(b=>!b.delete)}u(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);[...this.Da].forEach(b=>{b.u&&b.u(a)})}notify(a){let b=a.name;a=a.event;"keydown"==b&&this.ua?this.ua(a):"keyup"==b&&this.ka?this.ka(a):"mousemove"==b&&this.uc||("click"==b&&this.click?this.click(a):"control"==b&&this.control?this.control(a.key):"controlts"==b&&this.Pb?this.Pb(a.key):"controlte"==
b&&this.Ob?this.Ob(a.key):console.log(b))}uc(){}ka(a){this.control(a.key)}}const Ha=Math.PI,ia=(a,b=document)=>b.querySelector(a),Q=a=>0>a?-a:a,L=(a=1,b=0)=>0|((c=1,d=0)=>d+(c-d)*Math.random())(a,b),r=(a=0,b=0)=>{let c=document.createElement("canvas");return c.width=a,c.height=b,c},R=(a,b,c=!0)=>((d,e,f=!0)=>{var h,k,m,q;f&&0!=e%(Math.PI/4)?(m=d.width,q=d.height,h=k=Math.sqrt(m*m+q*q)):(h=d.width,k=d.height);f=r(h,k);m=f.getContext("2d");h/=2;k/=2;return m.imageSmoothingQuality="high",m.save(),m.translate(h,
k),m.rotate(e),m.drawImage(d,0,0,d.width,d.height,-d.width/2,-d.height/2,d.width,d.height),m.restore(),f})(a,(b%=8)*Ha/4,c),Z=(a,b,c,d,e)=>{let f=r(d,e);return f.getContext("2d").drawImage(a,b,c,d,e,0,0,d,e),f},g=(a,b=1,c=null)=>{let d=a.length,e=Math.max(...a.map(m=>m.length));var f=r(e*b,d*b),h=f.getContext("2d");for(let m=0;m<d;m++)for(let q=0;q<e;q++){var k=a[m][q];c&&(k=c(k));k&&""!=k&&(h.fillStyle=k,h.fillRect(q*b,m*b,b,b))}return f},aa=(a,b)=>{for(var c=a.getContext("2d").getImageData(0,0,
a.width,a.height).data,d=[],e=0;e<c.length;e+=4){var f=d,h=f.push;var k=c[e];var m=c[e+1],q=c[e+2];k=0==k+m+q+c[e+3]?null:0==k+m+q||255<k||255<m||255<q?"#000000":"#"+((k<<16)+(m<<8)+q).toString(16).padStart(6,"0");h.call(f,k)}c=[];for(e=0;e<a.height;e++)c[e]=[];f=e=0;for(h=0;h<d.length;h++)e>=a.width&&(f++,e=0),c[f][e]=d[h],b&&(c[f][e]=b(c[f][e])),e++;return c},z=(a,b,c="source-atop")=>{let d=r(a.width,a.height),e=d.getContext("2d");e.drawImage(a,0,0);e.globalCompositeOperation=c;for(c=0;c<a.width/
b.width;c++)for(let f=0;f<a.height/b.height;f++)e.drawImage(b,c*b.width,f*b.height);return d},ka=(a,b=!0)=>{let c=r(a.width,a.height),d=c.getContext("2d");return d.save(),b?(d.scale(-1,1),d.drawImage(a,0,0,-1*a.width,a.height)):(d.scale(1,-1),d.drawImage(a,0,0,a.width,-1*a.height)),d.restore(),c},M=a=>{var b=r(a[0].width,a[0].height),c=b.getContext("2d");for(let d in a)c.drawImage(a[d],0,0);return b};class A{constructor(){}static get(a,b,c,d,e="Arial",f=0,h=0){let k=r(1,1).getContext("2d");k.font=
b+"px "+e;f=r(parseInt(f||k.measureText(a).width||1),h||b+2);k=f.getContext("2d");k.font=b+"px "+e;k.fillStyle=c;k.fillText(a,0,b-2);d&&(f=z(f,d));a=r(f.width,f.height);b=a.getContext("2d");return b.fillStyle="#ffffff",b.drawImage(f,0,0),a}}var Ia=n(0,0,1,1),Ja=n(1,0,1,1),Ka=n(2,0,1,1),La=n(3,0,1,1),Ma=n(4,0,1,1),la=n(0,1,1,1),ma=n(1,1,1,1),na=n(2,1,1,1),Na=n(3,1,1,1),oa=n(4,1,1,1),pa=n(0,2,1,1),Oa=n(1,2,1,1),Pa=n(2,2,1,1),qa=n(0,3,1,1),ra=n(1,3,2,1),S=n(9,0,4,4),T=n(3,2,2,2),ba=n(0,4,2,2),sa=n(2,
4,2,2),ta=n(4,4,1,2),Qa=n(5,4,1,2),ua=n(6,4,1,2),va=n(7,4,2,2),wa=n(9,4,2,2),ca=n(5,0,2,2),da=n(5,2,2,2),ea=n(7,0,2,2),xa=n(7,2,2,2),Ra=n(11,4,1,1),Sa=n(0,6,2,2),Ta=n(2,6,2,2),Ua=n(4,6,2,2),Va=n(6,6,2,2),Wa=n(8,6,2,2),Xa=n(10,6,2,2),I=g(Ia,1),J=g(Ja,1),N=g(Ka,1),K=g(La,1),fa=g(Ma,1);g(la,1);g(ma,1);g(na,1);var U=g(Na,1);g(oa,1);g(pa,1);var Ya=g(Oa,1),Za=g(Pa,1);g(qa,1);g(ra,1);g(S,1);g(T,1);var ya=g(ba,1);g(sa,1);g(ta,1);g(Qa,1);g(ua,1);g(va,1);g(wa,1);g(ca,1);g(da,1);g(ea,1);g(xa,1);var za=g(Ra,
1),ha=g(Sa,1),$a=g(Ta,1),ab=g(Ua,1),bb=g(Va,1),cb=g(Wa,1),db=g(Xa,1);g(S,2);g(ca,2);g(da,2);g(T,2);class p{constructor(a,b){this.x=a;this.y=b}is(a){let b=this.y,c=a.y;return this.x==a.x&&b==c}I(a){if(!a)return 1/0;let b=this.x,c=this.y,d=a.x;a=a.y;if(b==d&&c==a)return 0;if(b==d)return Math.abs(c-a);if(c==a)return Math.abs(b-d);let e=0;return e+=Math.pow(b-d,2),e+=Math.pow(c-a,2),e=Math.sqrt(e),e}Va(a){let b=this.x,c=this.y,d=a.x;a=a.y;return b==d&&c==a?4:b>d?6:b<d?2:c<a?4:c>a?0:4}Ab(a,b){let c=this.clone();
return c.move(a,b),c}move(a,b){0==a?this.y-=b:4==a?this.y+=b:6==a?this.x-=b:2==a?this.x+=b:7==a?(this.y-=b,this.x-=b):1==a?(this.y-=b,this.x+=b):3==a?(this.y+=b,this.x+=b):5==a&&(this.y+=b,this.x-=b)}Ab(a,b){let c=this.clone();return c.move(a,b),c}wc(a,b){let c=a.x-this.x,d=a.y-this.y,e=Math.sqrt(c*c+d*d);e<b?(this.x=a.x,this.y=a.y):(this.x+=(c/e||0)*b,this.y+=(d/e||0)*b)}clone(){return new p(this.x,this.y)}u(a,b="red"){a.fillStyle=b;this.Ta(a,3,b)}Ta(a,b=4,c="green"){a.fillStyle=c;a.strokeStyle=
c;a.beginPath();a.arc(this.x,this.y,b,0,2*Math.PI);a.fill()}static Ta(a,b,c,d=1,e="green"){a.fillStyle=e;a.strokeStyle=e;a.beginPath();a.arc(b,c,d,0,2*Math.PI);a.fill()}}const V=[{aa:25,attack:1,m:1,name:"rabbit"},{aa:25,attack:4,m:5,name:"wolf"},{aa:25,attack:10,m:8,name:"deer"},{aa:25,attack:20,m:10,name:"bear"},{aa:25,attack:15,m:10,name:"npcman"},{aa:25,attack:10,m:10,name:"npcgirl"}];class E{constructor(a,b=0,c=null){this.type=b;this.g=a;this.C=this.S();this.l=this.C[this.type];this.h=c||a.Ub();
this.m=V[this.type].m;this.ma=V[this.type].m;this.fb=V[this.type].aa;this.ca=[]}vc(){var a=this.g.j;const b=this.g.Fb.vb(this.h.x/a,this.h.y/a,this.g.i.h.x/a,this.g.i.h.y/a);b&&2<=b.length?this.h=new p(b[1][0]*a,b[1][1]*a):console.log("no visible path to player")}update(a){this.time=a;this.fb--;0>=this.fb&&(this.fb=V[this.type].aa-this.g.H,this.vc(),this.h.I(this.g.i.h)<1.5*this.g.j&&(this.g.i.m-=this.type+1,this.g.i.Jb=3,console.log(this,"attacking player")))}Wa(){var a=r(this.l.width,3),b=a.getContext("2d");
b.fillStyle="green";return b.fillRect(0,0,this.m/this.ma*this.l.width,3),a}u(a){a.drawImage(this.l,this.h.x,this.h.y);this.m<this.ma&&a.drawImage(this.Wa(),this.h.x,this.h.y)}S(){if(E.X)return E.X;var a=this.g.K,b=this.g.j,c=D(g(qa,a),b,b,!1),d=D(g(ra,a),b,b,!1),e=D(g(wa,a),b,b,!1),f=g(va,a),h=g(ea,a),k=g(xa,a);a=g(la,a);this.L=this.w=b;return E.X=[c,d,e,f,h,k,a],E.X}}class eb extends E{constructor(a,b=0,c=null){super(a,b,c)}ra(){return gf.Xc(SPRITECOLORMATRIX.Zc,this.g.K,a=>"#bf0a0a"==a||"#990000"==
a?"#76428a":a)}u(a){super.u(a);a.drawImage(this.C[6],this.h.x+.65*this.l.width,this.h.y+.25*this.l.height)}}class Aa{constructor(a,b=2){this.g=a;this.gb=b;this.v=[];this.S(b)}kb(a){var b=this.g.j*this.gb;this.h=new p(a.x+this.g.j*this.gb/2,a.y+b/2);var c=new p(a.x,a.y+b),d=new p(a.x+this.g.j,a.y+b);a=new p(a.x+2*this.g.j,a.y+b);this.T=[c,d,a]}u(a){a.drawImage(this.Ea,this.h.x-this.Ea.width/2,this.h.y-this.Ea.width/2)}update(a){this.time=a;this.v=this.v.filter(c=>0<c.m);var b=Math.abs(this.h.x-this.g.i.h.x);
if(Math.abs(this.h.y-this.g.i.h.y)<=8*this.g.j&&b<=6*this.g.j)for(let c in this.T)(b=this.g.La(this.T[c].x,this.T[c].y))||(b=new eb(this.g,4,this.T[c]),this.v.push(b),this.g.v.push(b));[...this.v].forEach(c=>{c.update&&c.update(a)})}S(a=2){a=g(S,a);var b=aa(a),c=b.flat(),d=[...(new Set(c))];c={};for(f of d)for(c[f]=[],d=0;d<b.length;d++){c[f].push([]);for(var e=0;e<b[d].length;e++)b[d][e]===f?c[f][d][e]="#000000":c[f][d][e]=null}var f=(delete c.$c,c);var h=g(f["#6a6a6a"]),k=g(f["#c2c2c2"]);f=z(h,
u(I,.5));b=z(h,u(J,.5));c=z(h,u(N,.5));d=z(h,u(fa,.5));e=z(h,u(K,.5));h=z(h,u(U,.5));var m=z(k,u(I,.2)),q=z(k,u(J,.2)),t=z(k,u(N,.2)),y=z(k,u(fa,.2)),x=z(k,u(K,.2));k=z(k,u(U,.2));this.Ha=M([a,m,f]);this.ta=M([a,q,b]);this.oa=M([a,t,c]);this.Ea=M([a,y,d]);this.lb=M([a,x,e]);this.bb=M([a,k,h])}}class fb extends P{constructor(a){super(a);a=v(I,J);var b=v(K,I);this.ja=new Aa(this);this.i=g(ba,2);this.Ya=function(c,d,e,f,h=1){1<h&&(c=w(c,h),d=w(d,h));c=v(c,d);d=r(c.width*f,c.height*e);h=d.getContext("2d");
for(let k=0;k<e;k++)for(let m=0;m<f;m++)h.drawImage(c,k*c.height,m*c.width);return d}(a,b,this.s.canvas.width/8,this.s.canvas.height/8);this.Ya=u(this.Ya,.2);this.log=this.ec();this.buffer=this.qa();this.va=-20;this.Za=this.dc()}ec(){var a=r(400,200),b=a.getContext("2d"),c=v(I,J),d=v(K,K),e=v(J,N),f=v(N,I);return this.Z=[A.get("13th CENTURY\u2122",20,"green",f,"Arial Black"),A.get("ROBIN\u27b8HOOD ",40,"green",c,"Arial Black"),A.get("THE\u27b8OUTLAW ",28,"green",d,"Arial Black"),A.get("\u26051370s\u2235\u2234\u2235\u2234\u2235\u2234\u2235\u2234\u2235\u2234\u2235\u2234\u22352023\u2605",
15,"green",e,"Arial Black")],b.drawImage(l(this.Z[0],"white"),0,1),b.drawImage(this.Z[0],1,1),b.drawImage(l(this.Z[1],"red"),1,18),b.drawImage(this.Z[1],0,17),b.drawImage(l(this.Z[2],"white"),85,53),b.drawImage(this.Z[2],85,52),b.drawImage(this.Z[3],82,82),a}dc(){var a="you step into the legendary shoes of Robin Hood.;your mission is to make the world a better place.;- explore forest and hunt animals;- do quests and trade with merchants;- spread the wealth to the poor;- improve your stats and defend the village;a w s d / arrows for movement;e interact, q menue, space fire;explore forest hunt animal;trade with merchants;- give goodies to villagers for free (gain morale);- take quests from villagers for extra love;find old wizzard for a magic bow;more instructions can be learned in game".split(";"),
b=r(360,500);let c=b.getContext("2d");c.fillStyle="white";c.font="16px Arial";for(let d=0;d<a.length;d++)c.fillText(a[d],0,25*d+20);return b}update(a){this.time=a;this.va+=.8}qa(){let a=r(this.s.F.width,this.s.F.height),b=a.getContext("2d");b.drawImage(this.Ya,0,0);return b.drawImage(this.log,400>this.s.F.width?16:128,74),a}u(a){let b=20;a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);a.drawImage(this.buffer,0,0);a.fillStyle="green";
a.font="16px Arial";a.fillText("Time "+this.time,20,b);a.fillText("use any key to load menu ",20,b+20);a.drawImage(this.ja.Ha,16,192);a.drawImage(this.ja.ta,88,192);a.drawImage(this.ja.oa,160,192);a.drawImage(this.ja.Ea,232,192);a.drawImage(this.ja.lb,304,192);a.drawImage(this.ja.bb,376,192);a.drawImage(this.i,16,320);a.drawImage(Z(this.Za,0,this.va%this.Za.height,this.Za.width,200),64,320)}Ka(){100<this.va&&this.s.Oa();this.va=100}control(){this.Ka()}click(){this.Ka()}ua(){this.Ka()}ka(){this.Ka()}}
class gb{constructor(a,b=300,c=!0,d=!0,e=3){this.M=a;this.Nc=b;this.loop=e;this.pitch=d;this.ya=!1;this.P=new AudioContext;this.Cb=this.M;c&&this.start()}toggle(){this.ya?this.stop():this.start()}start(){this.ya=!0;this.Hb()}stop(){this.ya=!1}reset(){this.M=this.Cb}jc(a){switch(a){case "B":return 493.88;case "C":return 261.63;case "D":return 293.66;case "E":return 329.63;case "F":return 349.23;case "G":return 392}return 440}ac(a){var b=this.jc(a[0]);return 1<a.length?b*Math.pow(2,a[1]/12):b}Hb(){if(this.ya)if(0===
this.M.length&&0<this.loop&&(this.M=this.Cb,this.loop--),0===this.M.length)this.stop();else{var a=this.M[0];this.pitch?(this.M[1],this.M=this.M.slice(2)):this.M=this.M.slice(1);var b=this.P.createOscillator(),c=this.P.createGain();b.connect(c);c.connect(this.P.destination);b.frequency.setValueAtTime(this.ac(a),this.P.currentTime);b.start();c.gain.setValueAtTime(0,this.P.currentTime);c.gain.exponentialRampToValueAtTime(.05,this.P.currentTime+.02);setTimeout(()=>{c.gain.setValueAtTime(.05,this.P.currentTime);
c.gain.exponentialRampToValueAtTime(.001,this.P.currentTime+.02);b.stop(this.P.currentTime+.02);this.Hb()},60/this.Nc*1E3)}}}class hb extends P{constructor(a){super(a);this.C={lb:K,oa:N,Kb:za,ta:J,Ha:I,bb:U,i:ya};this.U=400>this.s.F.width?32:100;this.o=[{x:this.U,y:128},{x:this.U,y:160},{x:this.U,y:192},{x:this.U,y:224},{x:this.U,y:256},{x:this.U,y:288},{x:this.U,y:320}];this.xa="robin hood";this.A=0;this.Sa=this.da=!1;this.buffer=this.Mc()}Mc(){var a=r(this.s.F.width,this.s.F.height);return a.getContext("2d"),
a}update(a){this.time=a}u(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="green";a.font="16px Arial";a.drawImage(this.buffer,0,0);a.drawImage(A.get("\u2588 \u24c5\u24c1\u24b6\u24ce \u24bc\u24b6\u24c2\u24ba",24,"green",this.C.ta,"Verdana"),this.o[0].x+20,this.o[0].y);a.drawImage(A.get("\u2588 SOUND : "+(this.da&&1==this.da?"on":"off"),24,"green",this.C.oa,"Verdana"),this.o[1].x+20,this.o[1].y);a.drawImage(A.get("\u2588 Music : "+
(this.na&&this.na.ya?"on":"off"),24,"green",this.C.oa,"Verdana"),this.o[2].x+20,this.o[2].y);a.drawImage(A.get(`\u2588 NAME : ${this.xa}`,24,"green",this.C.oa,"Verdana"),this.o[3].x+20,this.o[3].y);a.drawImage(A.get("\u2588 Cheatmode : "+(this.Sa?"on":"off"),24,"green",this.C.Kb,"Verdana"),this.o[4].x+20,this.o[4].y);a.drawImage(A.get("\u2588 STATS \u32e1",24,"green",this.C.Ha,"Roboto"),this.o[5].x+20,this.o[5].y);a.drawImage(A.get("\u2588 GOD MODE : "+(this.yb?"on":"off"),24,"green",this.C.Kb,"Verdana"),
this.o[6].x+20,this.o[6].y);a.drawImage(this.C.i,this.o[this.A].x,this.o[this.A].y+4);a.fillText("Time "+this.time,20,20)}click(){}control(a){if("s"===a||"ArrowDown"===a)this.A=Q(this.A+1)%this.o.length;else if("w"===a||"ArrowUp"===a)0==this.A?this.A=this.o.length-1:this.A=Q(this.A-1)%this.o.length;else if("a"===a||"ArrowLeft"===a||"d"===a||"ArrowRight"===a||"space"===a||" "===a)0==this.A?(this.s.B||confirm("start new game?"))&&this.s.Pc():1==this.A?this.da?this.da=!1:this.da=!0:2==this.A?(this.na||
(this.na=new gb("E4E4D4E4E4D4E4G4G4A4A4E4E4D4E4E4D4E4G4G4A4A4G4G4E4E4D4E4E4D4E4A4A4",120,!1,!0,2E3)),this.na.toggle()):3==this.A?this.xa=(a=prompt("name",this.xa))&&0<a.length?a.substring(0,10):this.xa:4==this.A?(this.Sa=!0,this.s.B&&(this.s.B.i.N=1E7)):5==this.A?(this.na&&this.na.stop(),this.s.B?this.s.Rc():alert("start game before using this page")):6==this.A&&(this.yb=!0,this.s.B&&this.s.B.i.Ia())}ua(){}ka(a){this.control(a.key)}}class ib extends E{constructor(a,b=null){super(a,5,b);this.W=0;this.wa=
L(2,5)}Ma(){console.log("interacting with player");this.nc()}nc(){var a=L(this.W+this.g.H,this.W+this.g.H+this.wa),b=L(this.W+this.g.H,this.W+this.g.H+this.wa);console.log(`quest ${[a,b]}`);confirm(`Hello Robin, i have a quest for you,\nplease bring me ${a} apples and ${b} oranges for ${this.wa+this.g.H} points\n        `)&&(this.g.i.ba>=b&&this.g.i.$>=a?(this.g.i.ba-=b,this.g.i.$-=a,this.g.i.points+=this.wa+this.g.H,this.W++):alert("you dont have enough, trade with merchant in village"))}update(){}u(a){a.drawImage(this.l,
this.h.x,this.h.y)}}class jb extends E{constructor(a,b=null){super(a,5,b);this.l=this.ra();this.W=0;this.wa=1}ra(){return g(ea,this.g.K,a=>"#bf0a0a"==a||"#990000"==a?"#76428a":a)}Ma(){console.log("interacting with player");this.Xa()}Xa(){var a=this.g.H,b=this.W+this.g.H,c=L(a,b);a=L(a,b);b=this.g.H*(c+a);confirm(`Hello Robin, trade offer,\n${c} apples and ${a} oranges for ${b} $`)&&(this.g.i.N>=b?(this.g.i.ba+=a,this.g.i.$+=c,this.g.i.N-=b,this.W++):alert("you dont have enough cash, try hunting some animals"))}update(){}u(a){a.drawImage(this.l,
this.h.x,this.h.y)}}class kb extends E{constructor(a,b=null){super(a,5,b);this.l=this.ra()}ra(){var a=g(ua,this.g.K,b=>b);return D(a,this.g.j,this.g.j)}Ma(){console.log("interacting with player");this.Xa()}Xa(){confirm("Hello Robin, I offer you the magic bow for 1000000 $")&&(1E6<=this.g.i.N?alert("you have your skills, you dont need a magic bow"):alert("you dont have enough cash, try hunting some animals"))}update(){}u(a){a.drawImage(this.l,this.h.x,this.h.y)}}class lb{constructor(a,b=2){this.g=
a;this.gb=b;this.v=[];this.S(b)}kb(a){var b=this.l.height;this.h=new p(a.x+this.l.width/2,a.y+b/2);new p(a.x,a.y+b);var c=new p(a.x+this.g.j,a.y+b);new p(a.x+2*this.g.j,a.y+b);this.T=[c]}u(a){a.drawImage(this.l,this.h.x-this.l.width/2,this.h.y-this.l.height/2)}update(a){if(this.v=this.v.filter(c=>0<c.m),[...this.v].forEach(c=>{c.update&&c.update(a)}),this.time!=a&&(this.time=a,this.h.I(this.g.i.h)<=4.5*this.g.j))for(let c in this.T)if(!(b=this.g.La(this.T[c].x,this.T[c].y))){var b=new E(this.g,3,
this.T[c]);this.v.push(b);this.g.v.push(b)}}S(a=2){this.l=g(T,a)}}const W=[{n:"tree",D:1,c:"#0d3702"},{n:"brick",D:1,c:"#bf0a0a"},{n:"dirt",D:0,c:"#d9a066"},{n:"grass",D:0,c:"#99e550"},{n:"water",D:2,c:"#8a99f6"},{n:"steel",D:1,c:"#6a6a6a"},{n:"snow",D:0,c:"#dcdcdc"},{n:"player",D:0,c:"#130c40"},{n:"villager",D:1,c:"#fff300"},{n:"merchant",D:1,c:"#76428a"},{n:"wizzard",D:1,c:"#191919"},{n:"army",D:0,c:"#ff0000"},{n:"cave",D:1,c:"#2e2b2b"},{n:"deerspawnpoint",D:0,c:"#df7126"},{n:"rabbitspawnpoint",
D:0,c:"#d1d1d1"},{n:"wolfspawnpoint",D:0,c:"#898898"}],F=a=>{switch(a){case "#130c40":return"player";case "#fff300":return"villager";case "#76428a":return"merchant";case "#191919":return"wizzard";case "#a9a9a9":return"castle";case "#2e2b2b":return"cave";case "#df7126":return"spawner_deer";case "#d1d1d1":return"spawner_rabbit";case "#898898":return"spawner_wolf";default:return null}};class mb{constructor(a,b=1){this.B=a;this.Ec=w(I,4);this.Fc=w(J,4);this.Lc=w(N,4);this.Ic=w(za,4);this.Bc=w(fa,4);this.Jc=
w(K,4);this.Kc=g(oa,4);this.Cc=g(S,4);this.Gc=g(ca,4);this.Hc=g(da,4);this.Dc=g(T,4);this.Qa=[0,0];this.ia=[];this.pa=[];this.O=[];this.lc(b);this.hb=this.kc()}kc(){var a={};for(var b in W)a[W[b].c]=W[b].D;b=[];for(var c=0;c<this.O.length;c++){b[c]=[];for(var d=0;d<this.O[c].length;d++){var e=a[this.O[d][c]];b[c][d]=null!=e&&0==e?0:1}}return b}$a(a,b){return(a=Math.floor(a),b=Math.floor(b),0>a)||a>this.O.length-1||0>b||b>this.O.length-1||!this.O[a]?!0:this.qc(this.O[b][a])}qc(a){var b=W.find(c=>c.c==
a);return null==b?1:b.D}hc(){var a=ha.width,b=r(3*a,3*ha.height),c=b.getContext("2d");for(let d=0;3>d;d++)for(let e=0;3>e;e++)c.drawImage(ab,d*a,e*a);return c.drawImage(bb,a,0),c.drawImage(cb,2*a,2*a),c.drawImage(db,2*a,a),c.drawImage($a,0,0),c.drawImage(ha,a,a),b}fc(a,b=32){var c=[],d=[],e={},f=a.length,h=a[0].length;c=Array(f).fill(null).map(()=>Array(h).fill(null));d=Array(f).fill(null).map(()=>Array(h).fill(null));var k=new p(32,32),m=[],q=[];ja(a,(t,y,x)=>{if(c[y][x]=(C=>{switch(C){case "#99e550":return"grass";
case "#d9a066":return"dirt";case "#dcdcdc":return"snow";case "#8a99f6":return"water";default:return null}})(t)||"grass",d[y][x]=(C=>{switch(C){case "#0d3702":return"tree";case "#bf0a0a":return"brick";case "#6a6a6a":return"steel";case "#fbf236":return"house";case "#eca732":return"shop";default:return null}})(t)||null,e[F(t)]||(e[F(t)]=[]),F(t))(e[F(t)].push([y,x]),"player"==F(t))?k=new p(y*b,x*b):"villager"==F(t)?(m.push(new ib(this.B,new p(y*b,x*b))),console.log("villager added")):"merchant"==F(t)?
(m.push(new jb(this.B,new p(y*b,x*b))),console.log("merchant added")):"wizzard"==F(t)?(m.push(new kb(this.B,new p(y*b,x*b))),console.log("wizzard added")):"castle"==F(t)?(t=new Aa(this.B,4),t.kb({x:y*b,y:x*b}),q.push(t),console.log("castle added")):"cave"==F(t)&&(t=new lb(this.B,4),t.kb({x:y*b,y:x*b}),q.push(t),console.log("cave added"))});a=this.rb(c,b);f=this.rb(d,b);return{dd:c,ad:d,Oc:a,xc:f,Yc:e,zc:k,Uc:m,Nb:q}}rb(a,b=32){var c=r(a.length*b,a.length*b),d=c.getContext("2d");return ja(a,(e,f,h)=>
{var k=e?this.cc(e):null;e&&k&&d.drawImage(k,h*b,f*b)}),c}cc(a){switch(a){case "dirt":return this.Ec;case "grass":return this.Fc;case "water":return this.Lc;case "snow":return this.Ic;case "brick":return this.Bc;case "steel":return this.Jc;case "tree":return this.Kc;case "castle":return this.Cc;case "house":return this.Gc;case "shop":return this.Hc;case "cave":return this.Dc;default:return null}}lc(a=1){var b=this.hc();this.map=b;a*=16;this.O=b=aa(b);this.cb=b=this.fc(b,a);this.Qa=this.cb.zc;this.ia=
this.cb.Uc;this.pa=this.cb.Nb;this.sc=M([b.Oc,b.xc])}}class nb{constructor(a,b,c,d,e){this.wb=a;this.h=new p(0,0);this.L=c;this.w=b;this.Db=d;this.Eb=e}Yb(a){this.h=new p(a.x,a.y)}rc(a){this.h=a}move(a){this.h.move(a,32)}Zb(a){var b=this.h.x-this.w/2,c=this.h.y-this.L/2;return Z(a,0>b?0:b,0>c?0:c,this.w,this.L)}u(a,b){let c;let d,e,f,h,k,m;var q=this.h.y-this.L/2;c=this.h.x-this.w/2;0>=c&&(c=0,this.h.x=c+this.w/2);0>=q&&(q=0,this.h.y=q+this.L/2);c+this.w>b.width&&(c=b.width-this.w,this.h.x=c+this.w/
2);q+this.L>b.height&&(q=b.height-this.L,this.h.y=q+this.L/2);f=this.Db;h=this.Eb;d=k=this.w;e=m=this.L;a.drawImage(b,c,q,d,e,f,h,k,m)}bc(a,b,c=32){var d=this.h.x-this.w/2,e=this.h.y-this.L/2;a=a+(0>d?0:d)-this.Db;b=b+(0>e?0:e)-this.Eb;return a=Math.floor(a/c)*c,b=Math.floor(b/c)*c,new p(a,b)}}class Ba{constructor(){this.V=6;this.ga=this.ea=1;this.ha=10;this.fa=this.Y=1}Ia(){this.fa=this.Y=this.ha=this.ga=this.ea=this.V=15}static clone(a){var b=new Ba;b.V=a.V;b.ea=a.ea;b.ga=a.ga;b.ha=a.ha;b.Y=a.Y;
b.fa=a.fa}Ua(a){switch(a){case "ARCHERY":return this.V;case "HEALTH":return this.ea;case "POWER":return this.ga;case "SPEED":return this.ha;case "STELTH":return this.Y;case "LUCK":return this.fa;default:return 0}}Sb(a,b){switch(a){case "ARCHERY":this.V=b;break;case "HEALTH":this.ea=b;break;case "POWER":this.ga=b;break;case "SPEED":this.ha=b;break;case "STELTH":this.Y=b;break;case "LUCK":this.fa=b}}mc(){return[{n:"HEALTH",Ba:this.ea},{n:"POWER",Ba:this.ga},{n:"ARCHERY",Ba:this.V},{n:"SPEED",Ba:this.ha},
{n:"STELTH",Ba:this.Y},{n:"LUCK",Ba:this.fa}]}}class Ca{constructor(a){this.h=new p(a.x,a.y);this.m=1}u(a){a.drawImage(this.l,this.h.x,this.h.y)}}class O extends Ca{constructor(a){super(a.h);this.e=a;this.direction=a.direction;this.C=this.S();this.l=this.C[this.direction];this.width=this.l.width;this.height=this.l.height;this.speed=this.width;this.Qb=this.e.attributes.V;this.Bb=0;this.m=1}update(a){this.time=a;this.Bb++;this.Bb<this.Qb?(this.h.move(this.direction,this.speed),this.e.Mb(this)):this.m=
0}S(){if(O.X)return O.X;var a=this.e.g.K,b=16*a,c=D(g(na,a),b,b);a=R(c,0);b=R(c,2);var d=R(c,4);c=R(c,6);this.w=a.width;this.L=a.height;return O.X=[c,c,a,a,b,b,d,c],O.X}}class X extends Ca{constructor(a,b,c=1){super(b);this.g=a;this.value=c;this.l=this.$b()}update(a){this.time=a;this.h.I(this.g.i.h)<1.5*this.g.j&&(this.g.i.N+=this.value,this.m=0)}u(a){super.u(a)}$b(){if(X.nb)return X.nb;var a=this.g.j;a=D(g(pa,this.g.K),a,a,!1);return X.nb=a,a}}class ob{constructor(a){this.g=a;this.m=this.ma=100;
this.ba=this.$=this.points=this.N=this.za=0;this.attributes=new Ba(1);this.h=new p(0,0);this.destination=new p(0,0);this.Na=!1;this.time=0;this.direction=4;this.C=this.S();this.l=this.C[4];this.Ja=0;this.Aa=[];this.Pa=1E3}Ia(){this.m=this.Pa=this.ba=this.$=this.points=this.N=1E7;this.attributes.Ia()}xb(){var a=this.g.j*(12-this.attributes.Y);return a<=1.5*this.g.j&&(a=1.5*this.g.j),a}setPosition(a){this.h=new p(a.x,a.y);this.destination=new p(a.x,a.y)}update(a){this.Ja=Math.max(this.Ja-1,0);this.Aa=
this.Aa.filter(b=>0<b.m);[...this.Aa].forEach(b=>{b.update&&b.update(a)});this.time=a;0!=this.h.I(this.destination)?(this.Na=!0,this.h.wc(this.destination,this.l.width/2),this.g.Fa.Yb(this.h)):this.Na=!1;this.v=this.g.v.filter(b=>b.h.I(this.h)<this.xb());0<this.v.length&&[...this.v].forEach(b=>{b.update&&b.update(this.time)})}Xb(){0<this.Ja||(this.Ja=20-2*this.attributes.V,this.Pa--,this.Aa.push(new O(this)),this.yc())}Mb(a){var b=a.h;b=this.g.J.$a(b.x/this.g.j,b.y/this.g.j);1!=b&&1!=b||2==b||(a.m=
0,this.Gb());for(let c=0;c<this.g.v.length;c++)b=this.g.v[c],b.h.I(a.h)<this.g.j&&null!=b.type&&(b.m-=a.m,0>=b.m&&(this.g.v.push(new X(this.g,b.h,b.type+1)),5==b.type?this.za-=b.type+1:this.za+=b.type+1),this.Gb(),a.m=0)}Wa(){var a=r(this.l.width,3),b=a.getContext("2d");b.fillStyle="green";this.m<this.ma/2&&(b.fillStyle="orange");this.m<this.ma/2&&(b.fillStyle="red");return b.fillRect(0,0,this.m/this.ma*this.l.width,3),a}u(a){a.drawImage(this.l,this.h.x,this.h.y);4==this.direction?a.drawImage(this.R,
this.h.x+this.l.width-this.R.width,this.h.y+this.l.height-1.5*this.R.height):6==this.direction?a.drawImage(ka(this.R),this.h.x+this.l.width-1.6*this.R.width,this.h.y+this.l.height-1.3*this.R.height):2==this.direction&&a.drawImage(this.R,this.h.x+this.l.width-1.2*this.R.width,this.h.y+this.l.height-1.3*this.R.height);[...this.Aa].forEach(b=>{b.u&&b.u(a)});a.drawImage(this.Wa(),this.h.x,this.h.y);0<this.Jb&&(a.fillStyle="#ff0000aa",a.fillRect(this.h.x,this.h.y,this.l.width,this.l.height),this.Jb--);
this.Rb(a)}ib(a,b){this.direction=a=this.h.Va(new p(a,b));this.l=this.C[a]}moveTo(a,b){if(!this.g.sb(a,b)){var c=this.h.Va(new p(a,b));this.direction=c;0!=this.h.I(new p(a,b))&&(this.l=this.C[c],this.move(c))}}move(a){a===this.direction?this.Na||this.destination.move(a,this.width):this.direction=a}S(){this.R=g(ma,this.g.K);var a=g(ba,this.g.K),b=g(sa,this.g.K),c=g(ta,this.g.K);return this.width=a.width,this.height=a.height,[b,b,c=D(c,this.width,this.height),a,a,a,ka(c,!0),b]}ra(){return this.l}yc(){if(this.g.s.la.da){var a=
new (window.AudioContext||window.webkitAudioContext),b=a.createOscillator();b.type="sawtooth";b.frequency.setValueAtTime(500,a.currentTime);var c=a.createGain();c.gain.setValueAtTime(.2,a.currentTime);var d=a.createBiquadFilter();d.type="lowpass";d.frequency.setValueAtTime(500,a.currentTime);b.connect(c);c.connect(d);d.connect(a.destination);b.start();c.gain.exponentialRampToValueAtTime(.01,a.currentTime+.5);b.stop(a.currentTime+1)}}Gb(){if(this.g.s.la.da){var a=new (window.AudioContext||window.webkitAudioContext),
b=a.createOscillator();b.type="square";b.frequency.setValueAtTime(400,a.currentTime);var c=a.createGain();c.gain.setValueAtTime(.2,a.currentTime);var d=a.createBiquadFilter();d.type="lowpass";d.frequency.setValueAtTime(400,a.currentTime);b.connect(c);c.connect(d);d.connect(a.destination);b.start();c.gain.exponentialRampToValueAtTime(.01,a.currentTime+.5);b.stop(a.currentTime+1)}}Rb(a){var b=this.xb();0>=b||(a.beginPath(),a.arc(this.h.x+this.l.width/2,this.h.y+this.l.width/2,b,0,2*Math.PI,!1),a.setLineDash([5,
25]),a.strokeStyle="red",a.stroke(),a.setLineDash([]))}}class pb{constructor(a){this.tc=a;this.rows=a.length;this.cols=a[0].length}vb(a,b,c,d){a=Math.floor(a);b=Math.floor(b);c=Math.floor(c);d=Math.floor(d);const e=[],f=new Set,h={},k=Array(this.rows).fill(null).map(()=>Array(this.cols).fill(1/0));k[a][b]=0;const m=Array(this.rows).fill(null).map(()=>Array(this.cols).fill(1/0));m[a][b]=this.zb(a,b,c,d);for(e.push([a,b]);0<e.length;){a=this.Vb(e,m);const [q,t]=a;if(q===c&&t===d)return this.Ac(h,a);
e.splice(e.indexOf(a),1);f.add(`${q}-${t}`);b=this.ic(q,t);for(const y of b){const [x,C]=y;f.has(`${x}-${C}`)||this.tc[x][C]||(b=k[q][t]+1,b<k[x][C]&&(h[`${x}-${C}`]=a,k[x][C]=b,m[x][C]=b+this.zb(x,C,c,d),e.includes(y)||e.push(y)))}}return null}zb(a,b,c,d){return Math.abs(a-c)+Math.abs(b-d)}Vb(a,b){let c=a[0],d=b[c[0]][c[1]];for(const e of a){const [f,h]=e;b[f][h]<d&&(c=e,d=b[f][h])}return c}ic(a,b){const c=[];return 0<a&&c.push([a-1,b]),a<this.rows-1&&c.push([a+1,b]),0<b&&c.push([a,b-1]),b<this.cols-
1&&c.push([a,b+1]),c}Ac(a,b){const c=[b];for(;a.hasOwnProperty(`${b[0]}-${b[1]}`);)b=a[`${b[0]}-${b[1]}`],c.unshift(b);return c}}class qb extends P{constructor(a){super(a);this.oc()}oc(){this.H=1;this.Ca=5;this.K=2;this.j=16*this.K;this.keyboard={};this.J=new mb(this,this.K);this.eb=u(this.J.map,.7);this.i=new ob(this);this.s.la.Sa&&(this.i.N=1E7);this.s.la.yb&&this.i.Ia();this.i.setPosition(this.J.Qa?this.J.Qa:new p(224,224));this.Fa=new nb(this,this.s.F.width,this.s.F.height,0,0);this.Fa.rc(this.i.h);
this.xa="robin hood";this.ia=[...this.J.ia];this.pa=[...this.J.pa];this.v=[];this.hb=this.J.hb;this.Fb=new pb(this.hb);this.Tc=this.Wb();this.ub();this.ob()}La(a,b){a=Math.floor(a);b=Math.floor(b);a=new p(a,b);for(var c=0;c<this.ia.length;c++)if((b=this.ia[c]).h.I(a)<this.j)return b;for(c=0;c<this.v.length;c++)if((b=this.v[c]).h.I(a)<this.j)return b;return null}sb(a,b){return null!=this.La(a,b)||this.J.$a(a/this.j,b/this.j)}qa(){var a=r(this.s.F.width,this.s.F.height);let b=a.getContext("2d");b.clearRect(0,
0,b.canvas.width,b.canvas.height);b.fillStyle="black";b.fillRect(0,0,b.canvas.width,b.canvas.height);var c=(e=>{if(!e)return null;let f=r(e.width,e.height);return f.getContext("2d").drawImage(e,0,0),f})(this.J.sc),d=c.getContext("2d");if([...this.v].forEach(e=>{e.u&&e.u(d)}),[...this.ia].forEach(e=>{e.u&&e.u(d)}),[...this.pa].forEach(e=>{e.u&&e.u(d)}),this.i.u(d),this.ca)for(let e in this.ca)b.drawImage(u(this.i.l,.8),this.ca[e][0]*this.j,this.ca[e][1]*this.j);c=this.Fa.Zb(c);return b.drawImage(c,
0,0),a}update(a){this.time=a;this.v=this.v.filter(c=>0<c.m);this.i.update(a);for(var b in this.keyboard)this.keyboard[b]&&this.pb(b);if(0>=this.i.m&&(alert("game over"),this.s.B=null,this.i.m=100,this.s.Oa()),this.ca&&0<this.ca.length)b=this.ca.shift(),this.i.h=new p(b[0]*this.j,b[1]*this.j);0>=this.v.length&&(this.Ca+=5,this.H++,this.ob());[...this.pa].forEach(c=>{c.update&&c.update(a)})}ob(){for(let a=0;a<this.Ca&&!(this.v.length>this.Ca);a++){let b=new E(this,L(0,3));this.v.push(b)}}Wb(){var a=
[];for(let c=0;c<this.J.O.length;c++)for(let d=0;d<this.J.O.length;d++){var b=new p(c*this.j,d*this.j);this.J.$a(c,d)||a.push(b)}return a}Ub(){var a=this.ub(8,25);return 0<a.length?a[L(0,a.length)]:new p(this.j,this.j)}ub(a=8,b=13){var c=this.Tc;c=(c=c.filter(f=>f.I(this.i.h)>this.j*a)).filter(f=>f.I(this.i.h)<this.j*b);var d=[];for(let f in c){var e=!0;for(let h=0;h<this.v.length;h++)if(this.v[h].h.I(new p(c[f].x,c[f].y))<this.j){e=!1;break}e&&d.push(c[f])}return c}pc(){var a=this.i.h.Ab(this.i.direction,
this.j);(a=this.La(a.x,a.y))&&a.Ma?a.Ma():console.log(a)}pb(a){if(" "!==a&&"space"!==a||this.i.Xb(),"e"===a)this.pc(),this.keyboard={};else if("q"===a)this.keyboard.q=!1,this.s.Oa();else if(!this.i.Na){var b=this.i.h.clone(),c=!1;if("s"===a||"ArrowDown"===a?(b.move(4,this.i.height),c=!0):"w"===a||"ArrowUp"===a?(b.move(0,this.i.height),c=!0):"d"===a||"ArrowRight"===a?(b.move(2,this.i.height),c=!0):"a"!==a&&"ArrowLeft"!==a||(b.move(6,this.i.height),c=!0),c)a=this.i.h.Va(b),this.i.ib(b.x,b.y),a!=this.i.direction?
(this.i.ib(b.x,b.y),this.keyboard={}):this.sb(b.x,b.y)?this.i.ib(b.x,b.y):this.i.moveTo(b.x,b.y)}}u(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="green";a.font="16px Arial";a.drawImage(this.qa(),0,0);a.fillStyle="#004b52d6";a.fillRect(0,0,a.canvas.width,48);a.fillStyle="#ffffff";a.fillText("\u2665 "+H(this.i.m),15,15);a.fillText("\u2295 "+H(this.i.za),15,30);a.fillText("\u263a"+H(this.i.points),15,45);a.fillText("\u27b9\t"+
H(this.i.Pa),96,15);a.fillText("\u0556\t"+H(this.i.N),96,30);a.fillText("Mobs "+H(this.v.length),192,15);a.fillText("LVL "+H(this.H),192,30);a.drawImage(Ya,316,4);a.drawImage(Za,316,20);a.fillText("   "+H(this.i.$),320,15);a.fillText("   "+H(this.i.ba),320,30);a.drawImage(this.eb,0,a.canvas.height-this.eb.height);p.Ta(a,this.i.h.x/this.j,a.canvas.height-this.eb.height+this.i.h.y/this.j,3,"green")}click(a){var b=this.j;a=this.Fa.bc(a.offsetX,a.offsetY,b);a=new p(a.x,a.y);b=this.Fb.vb(this.i.h.x/b,
this.i.h.y/b,a.x/b,a.y/b);console.log(b)}control(a){this.pb(a)}ua(a){this.keyboard[a.key]=!0}ka(a){this.keyboard[a.key]=!1}}class rb{constructor(a){return this.target=a,this.mb=[],!!a.addEventListener}sub(a){this.mb.push(a)}clear(){this.mb=[]}fireEvent(a){var b=this.mb,c;for(c in b)b[c].notify&&b[c].notify(a)}}class sb extends P{constructor(a){super(a);this.C={lb:K,oa:N,ta:J,Ha:I,bb:U,i:ya};this.U=400>this.s.F.width?32:100;this.B=this.s.B;this.attributes=this.B.i.attributes;this.o=[];this.qb=this.attributes.mc();
for(let b in this.qb)this.o.push({x:this.U,y:192+32*b,k:this.qb[b].n});this.A=0;this.buffer=this.qa()}qa(){var a=r(this.s.F.width,this.s.F.height),b=a.getContext("2d"),c=this.o[0],d=c.x+20;b.drawImage(this.sa("\u2588\u2588\u2588\u2588 STATISTICS \u2588\u2588\u2588\u2588"),d,c.y-64);b.drawImage(this.sa("POINTS"),d,c.y-32);for(let e in this.o)c=this.o[e],b.drawImage(this.sa(`${c.k} `),d,c.y);return a}update(a){this.time=a}sa(a){return A.get(a,24,"white",this.C.ta)}u(a){a.clearRect(0,0,a.canvas.width,
a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="green";a.font="16px Arial";var b=this.o[0],c=b.x+20;a.drawImage(this.buffer,0,0);a.drawImage(this.sa(`${this.B.i.points}`),c+150,b.y-32);for(let d in this.o)b=this.o[d],a.drawImage(this.sa(`${this.B.i.attributes.Ua(b.k)}`),c+150,b.y);a.drawImage(this.C.i,this.o[this.A].x,this.o[this.A].y+4);a.fillText("Time "+this.time,20,20)}click(){}control(a){if("q"===a)this.s.Oa();else if("w"===a||"ArrowUp"===a)0==
this.A?this.A=this.o.length-1:this.A=Q(this.A-1)%this.o.length;else if("s"===a||"ArrowDown"===a)this.A=Q(this.A+1)%this.o.length;else if("d"==a||"ArrowRight"==a){if(0>=this.B.i.points)return void alert("no points to use");this.A;a=this.o[this.A].k;10<=this.B.i.attributes.Ua(a)?alert("level max reached"):confirm("spend points on upgrading skill "+a)&&(this.B.i.attributes.Sb(a,this.B.i.attributes.Ua(a)+1),--this.B.i.points)}}ua(){}ka(a){this.control(a.key)}}class tb{constructor(a){this.F=a;this.Ga=
document.querySelector(a.Ga);this.canvas=Object.assign(document.createElement("canvas"),{width:a.width,height:a.height,className:"gamecanvas"});this.Ga.appendChild(this.canvas);this.G=new rb(document);["keydown","keyup"].forEach(b=>{document.addEventListener(b,c=>{this.G.fireEvent({name:b,event:c})})});this.canvas.addEventListener("click",b=>{this.G.fireEvent({name:"click",event:b})});this.Qc();400>this.F.width&&(a.framerate/=2);this.Ra=new Ga(a.framerate,this,!0);this.Tb()}update(a){if(0==this.Ra.p)if(this.time=
a,this.g)try{this.g.update(a),this.g.u(this.canvas.getContext("2d"))}catch(b){console.log(b),this.Ra.stop()}else this.Ra.stop()}Qc(){this.g=new fb(this);this.G.clear();this.G.sub(this.g)}Oa(){this.la||(this.la=new hb(this));this.g=this.la;this.G.clear();this.G.sub(this.g)}Pc(){this.B||(this.B=new qb(this));this.g=this.B;this.G.clear();this.G.sub(this.g)}Rc(){this.Lb||(this.Lb=new sb(this));this.g=this.Lb;this.G.clear();this.G.sub(this.g)}Tb(){if(!(400<this.F.width)){var a=Object.assign(document.createElement("div"),
{className:"controls_container"});a.innerHTML="<table>\n        <tr><td id='q'>q</td><td id='w'>w</td><td id='e'>e</td><td class=\"padding\"></td><td id='space'>space</td> </tr>\n        <tr><td id='a'>a</td><td id='s'>s</td><td id='d'>d</td><td class=\"padding\"></td><td id='f'>f</td></tr></table>";this.Ga.appendChild(a);var b=((c,d=document)=>d.querySelectorAll(c))(".controls_container td");for(let c=0;c<b.length;c++)b[c].addEventListener("click",()=>{this.G.fireEvent({name:"control",event:{key:b[c].id}})}),
b[c].addEventListener("touchstart",()=>{this.G.fireEvent({name:"controlts",event:{key:b[c].id}})}),b[c].addEventListener("touchend",()=>{this.G.fireEvent({name:"controlte",event:{key:b[c].id}})})}}}const ub={Ga:".canvas_container",cd:32,Vc:1,framerate:1/30,width:32*parseInt(window.innerWidth/32),height:32*parseInt(window.innerHeight/32),Wc:"Assets",bd:ia("#spriteSheetMain")};class vb extends tb{constructor(a){super(a)}}document.addEventListener("DOMContentLoaded",function(){window.wb||(window.wb=
new vb(ub))},!1)})();
