var Da="function"==typeof Object.defineProperties?Object.defineProperty:function(l,v,w){if(l==Array.prototype||l==Object.prototype)return l;l[v]=w.value;return l};function Ea(l){l=["object"==typeof globalThis&&globalThis,l,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var v=0;v<l.length;++v){var w=l[v];if(w&&w.Math==Math)return w}throw Error("Cannot find global object");}var Fa=Ea(this);
function B(l,v){if(v)a:{var w=Fa;l=l.split(".");for(var u=0;u<l.length-1;u++){var D=l[u];if(!(D in w))break a;w=w[D]}l=l[l.length-1];u=w[l];v=v(u);v!=u&&null!=v&&Da(w,l,{configurable:!0,writable:!0,value:v})}}function G(l){l=Math.trunc(l)||0;0>l&&(l+=this.length);if(!(0>l||l>=this.length))return this[l]}B("Array.prototype.at",function(l){return l?l:G});function V(l){return l?l:G}B("Int8Array.prototype.at",V);B("Uint8Array.prototype.at",V);B("Uint8ClampedArray.prototype.at",V);
B("Int16Array.prototype.at",V);B("Uint16Array.prototype.at",V);B("Int32Array.prototype.at",V);B("Uint32Array.prototype.at",V);B("Float32Array.prototype.at",V);B("Float64Array.prototype.at",V);B("String.prototype.at",function(l){return l?l:G});
(()=>{function l(a,b,c="source-atop"){let d=r(a.width,a.height),e=d.getContext("2d");return e.drawImage(a,0,0),e.globalCompositeOperation=c,e.fillStyle=b,e.fillRect(0,0,d.width,d.height),d}function v(a,b){let c=r(a.width+b.width,a.height+b.height),d=c.getContext("2d");return d.drawImage(a,0,0),d.drawImage(a,a.width,b.height),d.drawImage(b,a.width,0),d.drawImage(b,0,a.height),c}function w(a,b,c=0){0==c&&(c=b);var d=r(a.width*c,a.height*b),e=d.getContext("2d");for(let f=0;f<b;f++)for(let h=0;h<c;h++)e.drawImage(a,
h*a.width,f*a.height);return d}function u(a,b){let c=r(a.width,a.height),d=c.getContext("2d");return d.globalAlpha=b,d.drawImage(a,0,0),d.globalAlpha=1,c}function D(a,b,c,d=!1){var e=r(b,c),f=e.getContext("2d");return d&&f.fillRect(0,0,b,c),f.drawImage(a,b/2-a.width/2,c/2-a.height/2),e}function H(a){return 1E9<a?parseInt(a/1E6)+"B":1E6<a?parseInt(a/1E6)+"M":1E3<a?parseInt(a/1E3)+"K":a}function n(a,b,c,d){let e=ia("#spriteSheetMain");a=W(e,8*a,8*b,8*c,8*d);return X(a,f=>"#ffffff"===f?"":f)}function ja(a,
b){for(var c=0;c<a.length;c++)for(var d=0;d<a[c].length;d++)b(a[d][c],c,d)}class Ga{constructor(a=1/30,b,c=!1){this.at=0;this.bb=null;this.sb=a;this.t=b;c&&this.start();this.p=this.jb=!1}Qc(a){if(this.bb)for(this.at+=(a-this.bb)/1E3,1<this.at&&(this.at=1);this.at>this.sb;){this.t.update(Math.floor(a/1E3));this.at-=this.sb;break}this.bb=a;this.jb||this.Hb()}Hb(){requestAnimationFrame(a=>{this.Qc(a)})}start(){this.jb=!1;this.Hb()}stop(){this.jb=!0}}class P{constructor(a){this.o=a;this.Ca=[]}update(a){this.time=
a;[...this.Ca].forEach(b=>{b.update&&b.update(a)});this.Ca=this.Ca.filter(b=>!b.delete)}s(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);[...this.Ca].forEach(b=>{b.s&&b.s(a)})}notify(a){let b=a.name;a=a.event;"keydown"==b&&this.ra?this.ra(a):"keyup"==b&&this.ia?this.ia(a):"mousemove"==b&&this.uc||("click"==b&&this.click?this.click(a):"control"==b&&this.control?this.control(a.key):"controlts"==b&&this.Pb?this.Pb(a.key):"controlte"==
b&&this.Ob&&this.Ob(a.key))}uc(){}ia(a){this.control(a.key)}}const Ha=Math.PI,ia=(a,b=document)=>b.querySelector(a),Q=a=>0>a?-a:a,I=(a=1,b=0)=>0|((c=1,d=0)=>d+(c-d)*Math.random())(a,b),r=(a=0,b=0)=>{let c=document.createElement("canvas");return c.width=a,c.height=b,c},R=(a,b,c=!0)=>((d,e,f=!0)=>{var h,k,m,p;f&&0!=e%(Math.PI/4)?(m=d.width,p=d.height,h=k=Math.sqrt(m*m+p*p)):(h=d.width,k=d.height);f=r(h,k);m=f.getContext("2d");h/=2;k/=2;return m.imageSmoothingQuality="high",m.save(),m.translate(h,k),
m.rotate(e),m.drawImage(d,0,0,d.width,d.height,-d.width/2,-d.height/2,d.width,d.height),m.restore(),f})(a,(b%=8)*Ha/4,c),W=(a,b,c,d,e)=>{let f=r(d,e);return f.getContext("2d").drawImage(a,b,c,d,e,0,0,d,e),f},g=(a,b=1,c=null)=>{let d=a.length,e=Math.max(...a.map(m=>m.length));var f=r(e*b,d*b),h=f.getContext("2d");for(let m=0;m<d;m++)for(let p=0;p<e;p++){var k=a[m][p];c&&(k=c(k));k&&""!=k&&(h.fillStyle=k,h.fillRect(p*b,m*b,b,b))}return f},X=(a,b)=>{for(var c=a.getContext("2d").getImageData(0,0,a.width,
a.height).data,d=[],e=0;e<c.length;e+=4){var f=d,h=f.push;var k=c[e];var m=c[e+1],p=c[e+2];k=0==k+m+p+c[e+3]?null:0==k+m+p||255<k||255<m||255<p?"#000000":"#"+((k<<16)+(m<<8)+p).toString(16).padStart(6,"0");h.call(f,k)}c=[];for(e=0;e<a.height;e++)c[e]=[];f=e=0;for(h=0;h<d.length;h++)e>=a.width&&(f++,e=0),c[f][e]=d[h],b&&(c[f][e]=b(c[f][e])),e++;return c},z=(a,b,c="source-atop")=>{let d=r(a.width,a.height),e=d.getContext("2d");e.drawImage(a,0,0);e.globalCompositeOperation=c;for(c=0;c<a.width/b.width;c++)for(let f=
0;f<a.height/b.height;f++)e.drawImage(b,c*b.width,f*b.height);return d},ka=(a,b=!0)=>{let c=r(a.width,a.height),d=c.getContext("2d");return d.save(),b?(d.scale(-1,1),d.drawImage(a,0,0,-1*a.width,a.height)):(d.scale(1,-1),d.drawImage(a,0,0,a.width,-1*a.height)),d.restore(),c},L=a=>{var b=r(a[0].width,a[0].height),c=b.getContext("2d");for(let d in a)c.drawImage(a[d],0,0);return b};class A{constructor(){}static get(a,b,c,d,e="Arial",f=0,h=0){let k=r(1,1).getContext("2d");k.font=b+"px "+e;f=r(parseInt(f||
k.measureText(a).width||1),h||b+2);k=f.getContext("2d");k.font=b+"px "+e;k.fillStyle=c;k.fillText(a,0,b-2);d&&(f=z(f,d));a=r(f.width,f.height);b=a.getContext("2d");return b.fillStyle="#ffffff",b.drawImage(f,0,0),a}}var Ia=n(0,0,1,1),Ja=n(1,0,1,1),Ka=n(2,0,1,1),La=n(3,0,1,1),Ma=n(4,0,1,1),la=n(0,1,1,1),ma=n(1,1,1,1),na=n(2,1,1,1),Na=n(3,1,1,1),oa=n(4,1,1,1),pa=n(0,2,1,1),Oa=n(1,2,1,1),Pa=n(2,2,1,1),qa=n(0,3,1,1),ra=n(1,3,2,1),Y=n(9,0,4,4),Z=n(3,2,2,2),aa=n(0,4,2,2),sa=n(2,4,2,2),ta=n(4,4,1,2),Qa=n(5,
4,1,2),ua=n(6,4,1,2),va=n(7,4,2,2),wa=n(9,4,2,2),ba=n(5,0,2,2),ca=n(5,2,2,2),da=n(7,0,2,2),xa=n(7,2,2,2),Ra=n(11,4,1,1),Sa=n(0,6,2,2),Ta=n(2,6,2,2),Ua=n(4,6,2,2),Va=n(6,6,2,2),Wa=n(8,6,2,2),Xa=n(10,6,2,2),J=g(Ia,1),K=g(Ja,1),N=g(Ka,1),M=g(La,1),ea=g(Ma,1);g(la,1);g(ma,1);g(na,1);var fa=g(Na,1);g(oa,1);g(pa,1);var Ya=g(Oa,1),Za=g(Pa,1);g(qa,1);g(ra,1);g(Y,1);g(Z,1);var ya=g(aa,1);g(sa,1);g(ta,1);g(Qa,1);g(ua,1);g(va,1);g(wa,1);g(ba,1);g(ca,1);g(da,1);g(xa,1);var za=g(Ra,1),ha=g(Sa,1),$a=g(Ta,1),ab=
g(Ua,1),bb=g(Va,1),cb=g(Wa,1),db=g(Xa,1);g(Y,2);g(ba,2);g(ca,2);g(Z,2);class q{constructor(a,b){this.x=a;this.y=b}is(a){let b=this.y,c=a.y;return this.x==a.x&&b==c}I(a){if(!a)return 1/0;let b=this.x,c=this.y,d=a.x;a=a.y;if(b==d&&c==a)return 0;if(b==d)return Math.abs(c-a);if(c==a)return Math.abs(b-d);let e=0;return e+=Math.pow(b-d,2),e+=Math.pow(c-a,2),e=Math.sqrt(e),e}Wa(a){let b=this.x,c=this.y,d=a.x;a=a.y;return b==d&&c==a?4:b>d?6:b<d?2:c<a?4:c>a?0:4}Ab(a,b){let c=this.clone();return c.move(a,b),
c}move(a,b){0==a?this.y-=b:4==a?this.y+=b:6==a?this.x-=b:2==a?this.x+=b:7==a?(this.y-=b,this.x-=b):1==a?(this.y-=b,this.x+=b):3==a?(this.y+=b,this.x+=b):5==a&&(this.y+=b,this.x-=b)}Ab(a,b){let c=this.clone();return c.move(a,b),c}wc(a,b){let c=a.x-this.x,d=a.y-this.y,e=Math.sqrt(c*c+d*d);e<b?(this.x=a.x,this.y=a.y):(this.x+=(c/e||0)*b,this.y+=(d/e||0)*b)}clone(){return new q(this.x,this.y)}s(a,b="red"){a.fillStyle=b;this.Ua(a,3,b)}Ua(a,b=4,c="green"){a.fillStyle=c;a.strokeStyle=c;a.beginPath();a.arc(this.x,
this.y,b,0,2*Math.PI);a.fill()}static Ua(a,b,c,d=1,e="green"){a.fillStyle=e;a.strokeStyle=e;a.beginPath();a.arc(b,c,d,0,2*Math.PI);a.fill()}}const S=[{aa:25,D:1,na:1},{aa:25,D:5,na:4},{aa:25,D:8,na:10},{aa:25,D:9,na:20},{aa:25,D:9,na:15},{aa:25,D:9,na:10}];class E{constructor(a,b=0,c=null){this.type=b;this.g=a;this.C=this.$();this.j=this.C[this.type];this.h=c||a.Ub();this.A=S[this.type].D;this.ja=S[this.type].D;this.fb=S[this.type].aa;this.ca=[]}vc(){var a=this.g.l;const b=this.g.Fb.ub(this.h.x/a,
this.h.y/a,this.g.i.h.x/a,this.g.i.h.y/a);b&&2<=b.length&&(this.h=new q(b[1][0]*a,b[1][1]*a))}update(a){this.time=a;this.fb--;0>=this.fb&&(this.fb=S[this.type].aa-this.g.K,this.vc(),this.h.I(this.g.i.h)<1.5*this.g.l&&(this.g.i.A-=this.type+1,this.g.i.Ib=3))}Xa(a){if(this.A!=this.ja){var b=r(this.j.width,3),c=b.getContext("2d");c.fillStyle="green";c.fillRect(0,0,this.A/this.ja*this.j.width,3);a.drawImage(b,this.h.x,this.h.y)}}s(a){a.drawImage(this.j,this.h.x,this.h.y);this.Xa(a)}$(){if(E.W)return E.W;
var a=this.g.M,b=this.g.l,c=D(g(qa,a),b,b,!1),d=D(g(ra,a),b,b,!1),e=D(g(wa,a),b,b,!1),f=g(va,a),h=g(da,a),k=g(xa,a);a=g(la,a);this.D=this.w=b;return E.W=[c,d,e,f,h,k,a],E.W}}class eb extends E{constructor(a,b=0,c=null){super(a,b,c)}s(a){super.s(a);a.drawImage(this.C[6],this.h.x+.65*this.j.width,this.h.y+.25*this.j.height)}}class Aa{constructor(a,b=2){this.g=a;this.gb=b;this.u=[];this.$(b)}kb(a){var b=this.g.l*this.gb;this.h=new q(a.x+this.g.l*this.gb/2,a.y+b/2);var c=new q(a.x,a.y+b),d=new q(a.x+
this.g.l,a.y+b);a=new q(a.x+2*this.g.l,a.y+b);this.S=[c,d,a]}s(a){a.drawImage(this.Da,this.h.x-this.Da.width/2,this.h.y-this.Da.width/2)}update(a){this.time=a;this.u=this.u.filter(c=>0<c.A);var b=Math.abs(this.h.x-this.g.i.h.x);if(Math.abs(this.h.y-this.g.i.h.y)<=8*this.g.l&&b<=6*this.g.l)for(let c in this.S)(b=this.g.Ka(this.S[c].x,this.S[c].y))||(b=new eb(this.g,4,this.S[c]),this.u.push(b),this.g.u.push(b));[...this.u].forEach(c=>{c.update&&c.update(a)})}$(a=2){a=g(Y,a);var b=X(a),c=b.flat(),d=
[...(new Set(c))];c={};for(f of d)for(c[f]=[],d=0;d<b.length;d++){c[f].push([]);for(var e=0;e<b[d].length;e++)b[d][e]===f?c[f][d][e]="#000000":c[f][d][e]=null}var f=(delete c.Wc,c);var h=g(f["#6a6a6a"]),k=g(f["#c2c2c2"]);f=z(h,u(J,.5));b=z(h,u(K,.5));c=z(h,u(N,.5));d=z(h,u(ea,.5));e=z(h,u(M,.5));h=z(h,u(fa,.5));var m=z(k,u(J,.2)),p=z(k,u(K,.2)),t=z(k,u(N,.2)),y=z(k,u(ea,.2)),x=z(k,u(M,.2));k=z(k,u(fa,.2));this.Ta=L([a,m,f]);this.qa=L([a,p,b]);this.Aa=L([a,t,c]);this.Da=L([a,y,d]);this.Lb=L([a,x,e]);
this.zb=L([a,k,h])}}class fb extends P{constructor(a){super(a);a=v(J,K);var b=v(M,J);this.ha=new Aa(this);this.i=g(aa,2);this.Za=function(c,d,e,f,h=1){1<h&&(c=w(c,h),d=w(d,h));c=v(c,d);d=r(c.width*f,c.height*e);h=d.getContext("2d");for(let k=0;k<e;k++)for(let m=0;m<f;m++)h.drawImage(c,k*c.height,m*c.width);return d}(a,b,this.o.canvas.width/8,this.o.canvas.height/8);this.Za=u(this.Za,.2);this.log=this.ec();this.buffer=this.oa();this.sa=-20;this.$a=this.dc()}ec(){var a=r(400,200),b=a.getContext("2d"),
c=v(J,K),d=v(M,M),e=v(K,N),f=v(N,J);return this.Y=[A.get("13th CENTURY\u2122",20,"green",f,"Arial Black"),A.get("ROBIN\u27b8HOOD ",40,"green",c,"Arial Black"),A.get("THE\u27b8OUTLAW ",28,"green",d,"Arial Black"),A.get("\u26051370s\u2235\u2234\u2235\u2234\u2235\u2234\u2235\u2234\u2235\u2234\u2235\u2234\u22352023\u2605",15,"green",e,"Arial Black")],b.drawImage(l(this.Y[0],"white"),0,1),b.drawImage(this.Y[0],1,1),b.drawImage(l(this.Y[1],"red"),1,18),b.drawImage(this.Y[1],0,17),b.drawImage(l(this.Y[2],
"white"),85,53),b.drawImage(this.Y[2],85,52),b.drawImage(this.Y[3],82,82),a}dc(){var a="you step into the legendary shoes of Robin Hood.;your mission is to make the world a better place.;- explore forest and hunt animals;- trade with merchants;- take quest from villagers;- improve your stats and defend the village;a w s d / arrows for movement;e interact, q menue, space fire".split(";"),b=r(360,500);let c=b.getContext("2d");c.fillStyle="white";c.font="16px Arial";for(let d=0;d<a.length;d++)c.fillText(a[d],
0,25*d+20);return b}update(a){this.time=a;this.sa+=.8}oa(){let a=r(this.o.G.width,this.o.G.height),b=a.getContext("2d");b.drawImage(this.Za,0,0);return b.drawImage(this.log,400>this.o.G.width?16:128,74),a}s(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);a.drawImage(this.buffer,0,0);a.drawImage(this.ha.Ta,16,192);a.drawImage(this.ha.qa,88,192);a.drawImage(this.ha.Aa,160,192);a.drawImage(this.ha.Da,232,192);a.drawImage(this.ha.Lb,
304,192);a.drawImage(this.ha.zb,376,192);a.drawImage(this.i,16,320);a.drawImage(W(this.$a,0,this.sa%this.$a.height,this.$a.width,200),64,320)}Ja(){100<this.sa&&this.o.Oa();this.sa=100}control(){this.Ja()}click(){this.Ja()}ra(){this.Ja()}ia(){this.Ja()}}class gb{constructor(a,b=300,c=!0,d=!0,e=3){this.L=a;this.Lc=b;this.loop=e;this.pitch=d;this.va=!1;this.P=new AudioContext;this.Cb=this.L;c&&this.start()}toggle(){this.va?this.stop():this.start()}start(){this.va=!0;this.Gb()}stop(){this.va=!1}reset(){this.L=
this.Cb}jc(a){switch(a){case "B":return 493.88;case "C":return 261.63;case "D":return 293.66;case "E":return 329.63;case "F":return 349.23;case "G":return 392}return 440}ac(a){var b=this.jc(a[0]);return 1<a.length?b*Math.pow(2,a[1]/12):b}Gb(){if(this.va)if(0===this.L.length&&0<this.loop&&(this.L=this.Cb,this.loop--),0===this.L.length)this.stop();else{var a=this.L[0];this.pitch?(this.L[1],this.L=this.L.slice(2)):this.L=this.L.slice(1);var b=this.P.createOscillator(),c=this.P.createGain();b.connect(c);
c.connect(this.P.destination);b.frequency.setValueAtTime(this.ac(a),this.P.currentTime);b.start();c.gain.setValueAtTime(0,this.P.currentTime);c.gain.exponentialRampToValueAtTime(.05,this.P.currentTime+.02);setTimeout(()=>{c.gain.setValueAtTime(.05,this.P.currentTime);c.gain.exponentialRampToValueAtTime(.001,this.P.currentTime+.02);b.stop(this.P.currentTime+.02);this.Gb()},60/this.Lc*1E3)}}}class hb extends P{constructor(a){super(a);this.C={Lb:M,Aa:N,Jb:za,qa:K,Ta:J,zb:fa,i:ya};this.T=400>this.o.G.width?
32:100;this.m=[{x:this.T,y:128},{x:this.T,y:160},{x:this.T,y:192},{x:this.T,y:224},{x:this.T,y:256},{x:this.T,y:288},{x:this.T,y:320}];this.ua="robin hood";this.v=0;this.Sa=this.la=!1;this.buffer=this.Kc()}Kc(){var a=r(this.o.G.width,this.o.G.height);return a.getContext("2d"),a}update(a){this.time=a}s(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="green";a.font="16px Arial";a.drawImage(this.buffer,0,0);a.drawImage(A.get("\u2588 \u24c5\u24c1\u24b6\u24ce \u24bc\u24b6\u24c2\u24ba",
24,"green",this.C.qa,"Verdana"),this.m[0].x+20,this.m[0].y);a.drawImage(A.get("\u2588 SOUND : "+(this.la&&1==this.la?"on":"off"),24,"green",this.C.Aa,"Verdana"),this.m[1].x+20,this.m[1].y);a.drawImage(A.get("\u2588 Music : "+(this.ka&&this.ka.va?"on":"off"),24,"green",this.C.Aa,"Verdana"),this.m[2].x+20,this.m[2].y);a.drawImage(A.get(`\u2588 NAME : ${this.ua}`,24,"green",this.C.Aa,"Verdana"),this.m[3].x+20,this.m[3].y);a.drawImage(A.get("\u2588 Cheatmode : "+(this.Sa?"on":"off"),24,"green",this.C.Jb,
"Verdana"),this.m[4].x+20,this.m[4].y);a.drawImage(A.get("\u2588 STATS \u32e1",24,"green",this.C.Ta,"Verdana"),this.m[5].x+20,this.m[5].y);a.drawImage(A.get("\u2588 GOD MODE : "+(this.xb?"on":"off"),24,"green",this.C.Jb,"Verdana"),this.m[6].x+20,this.m[6].y);a.drawImage(this.C.i,this.m[this.v].x,this.m[this.v].y+4);a.fillText("Time "+this.time,20,20)}click(){}control(a){if("s"===a||"ArrowDown"===a)this.v=Q(this.v+1)%this.m.length;else if("w"===a||"ArrowUp"===a)0==this.v?this.v=this.m.length-1:this.v=
Q(this.v-1)%this.m.length;else if("a"===a||"ArrowLeft"===a||"d"===a||"ArrowRight"===a||"space"===a||" "===a)0==this.v?(this.o.B||confirm("start new game?"))&&this.o.Nc():1==this.v?this.la?this.la=!1:this.la=!0:2==this.v?(this.ka||(this.ka=new gb("E4E4D4E4E4D4E4G4G4A4A4E4E4D4E4E4D4E4G4G4A4A4G4G4E4E4D4E4E4D4E4A4A4",120,!1,!0,2E3)),this.ka.toggle()):3==this.v?this.ua=(a=prompt("name",this.ua))&&0<a.length?a.substring(0,10):this.ua:4==this.v?(this.Sa=!0,this.o.B&&(this.o.B.i.N=1E7)):5==this.v?(this.ka&&
this.ka.stop(),this.o.B?this.o.Pc():alert("start game before using this page")):6==this.v&&(this.xb=!0,this.o.B&&this.o.B.i.Ga())}ra(){}ia(a){this.control(a.key)}}class ib extends E{constructor(a,b=null){super(a,5,b);this.ya=0;this.Na=I(2,5)}La(){this.nc()}nc(){var a=I(0,this.ya),b=I(a+this.g.K,a+this.g.K+this.Na);a=I(a+this.g.K,a+this.g.K+this.Na);var c=(this.Na+this.g.K)*this.g.i.attributes.V;confirm(`Quest\n ${b} apples and ${a} oranges for ${c} points`)&&(this.g.i.ba>=a&&this.g.i.Z>=b?(this.g.i.ba-=
a,this.g.i.Z-=b,this.g.i.points+=c,this.ya++):alert("insufficient materials"))}update(){}s(a){a.drawImage(this.j,this.h.x,this.h.y)}}class jb extends E{constructor(a,b=null){super(a,5,b);this.j=this.Ia();this.ya=0;this.Na=1}Ia(){return g(da,this.g.M,a=>"#bf0a0a"==a||"#990000"==a?"#76428a":a)}La(){this.Ya()}Ya(){var a=this.g.K,b=this.ya+this.g.K,c=I(a,b);a=I(a,b);b=this.g.K*(c+a);0>=(b-=I(0,this.g.i.attributes.V*b/2))&&(b=1);confirm(`trade offer\n${c} apples and ${a} oranges for ${b} $`)&&(this.g.i.N>=
b?(this.g.i.ba+=a,this.g.i.Z+=c,this.g.i.N-=b,this.ya++):alert("not enough cash"))}update(){}s(a){a.drawImage(this.j,this.h.x,this.h.y)}}class kb extends E{constructor(a,b=null){super(a,5,b);this.j=this.Ia()}Ia(){var a=g(ua,this.g.M,b=>b);return D(a,this.g.l,this.g.l)}La(){this.Ya()}Ya(){confirm("magic bow 1000000 $")&&(1E6<=this.g.i.N?alert("you have your skills, you dont need a magic bow"):alert("insufficient cash"))}update(){}s(a){a.drawImage(this.j,this.h.x,this.h.y)}}class lb{constructor(a,b=
2){this.g=a;this.gb=b;this.u=[];this.j=g(Z,b)}kb(a){var b=this.j.height;this.h=new q(a.x+this.j.width/2,a.y+b/2);this.S=[new q(a.x+this.g.l,a.y+b)]}s(a){a.drawImage(this.j,this.h.x-this.j.width/2,this.h.y-this.j.height/2)}update(a){if(this.u=this.u.filter(c=>0<c.A),[...this.u].forEach(c=>{c.update&&c.update(a)}),this.time!=a&&(this.time=a,this.h.I(this.g.i.h)<=4.5*this.g.l))for(let c in this.S)if(!(b=this.g.Ka(this.S[c].x,this.S[c].y))){var b=new E(this.g,3,this.S[c]);this.u.push(b);this.g.u.push(b)}}}
const T=[{n:"p",F:1,c:"#0d3702"},{n:"p",F:1,c:"#bf0a0a"},{n:"p",F:0,c:"#d9a066"},{n:"p",F:0,c:"#99e550"},{n:"p",F:2,c:"#8a99f6"},{n:"p",F:1,c:"#6a6a6a"},{n:"p",F:0,c:"#dcdcdc"},{n:"p",F:0,c:"#130c40"},{n:"p",F:1,c:"#fff300"},{n:"p",F:1,c:"#76428a"},{n:"p",F:1,c:"#191919"},{n:"p",F:0,c:"#ff0000"},{n:"p",F:1,c:"#2e2b2b"},{n:"p",F:0,c:"#df7126"},{n:"p",F:0,c:"#d1d1d1"},{n:"p",F:0,c:"#898898"}],F=a=>{switch(a){case "#130c40":return"player";case "#fff300":return"villager";case "#76428a":return"merchant";
case "#191919":return"wizzard";case "#a9a9a9":return"castle";case "#2e2b2b":return"cave"}return null};class mb{constructor(a,b=1){this.B=a;this.Cc=w(J,4);this.Dc=w(K,4);this.Jc=w(N,4);this.Gc=w(za,4);this.Bc=w(ea,4);this.Hc=w(M,4);this.Ic=g(oa,4);this.Ec=g(ba,4);this.Fc=g(ca,4);this.Qa=[0,0];this.ga=[];this.ma=[];this.O=[];this.lc(b);this.hb=this.kc()}kc(){var a={};for(var b in T)a[T[b].c]=T[b].F;b=[];for(var c=0;c<this.O.length;c++){b[c]=[];for(var d=0;d<this.O[c].length;d++){var e=a[this.O[d][c]];
b[c][d]=null!=e&&0==e?0:1}}return b}ab(a,b){return(a=Math.floor(a),b=Math.floor(b),0>a)||a>this.O.length-1||0>b||b>this.O.length-1||!this.O[a]?!0:this.qc(this.O[b][a])}qc(a){var b=T.find(c=>c.c==a);return null==b?1:b.F}hc(){var a=ha.width,b=r(3*a,3*ha.height),c=b.getContext("2d");for(let d=0;3>d;d++)for(let e=0;3>e;e++)c.drawImage(ab,d*a,e*a);return c.drawImage(bb,a,0),c.drawImage(cb,2*a,2*a),c.drawImage(db,2*a,a),c.drawImage($a,0,0),c.drawImage(ha,a,a),b}fc(a,b=32){var c=[],d=[],e={},f=a.length,
h=a[0].length;c=Array(f).fill(null).map(()=>Array(h).fill(null));d=Array(f).fill(null).map(()=>Array(h).fill(null));var k=new q(32,32),m=[],p=[];ja(a,(t,y,x)=>{if(c[y][x]=(C=>{switch(C){case "#99e550":return"grass";case "#d9a066":return"dirt";case "#dcdcdc":return"snow";case "#8a99f6":return"water"}return null})(t)||"grass",d[y][x]=(C=>{switch(C){case "#0d3702":return"tree";case "#bf0a0a":return"brick";case "#6a6a6a":return"steel";case "#fbf236":return"house";case "#eca732":return"shop"}return null})(t)||
null,e[F(t)]||(e[F(t)]=[]),F(t))(e[F(t)].push([y,x]),"player"==F(t))?k=new q(y*b,x*b):"villager"==F(t)?m.push(new ib(this.B,new q(y*b,x*b))):"merchant"==F(t)?m.push(new jb(this.B,new q(y*b,x*b))):"wizzard"==F(t)?m.push(new kb(this.B,new q(y*b,x*b))):"castle"==F(t)?(t=new Aa(this.B,4),t.kb({x:y*b,y:x*b}),p.push(t)):"cave"==F(t)&&(t=new lb(this.B,4),t.kb({x:y*b,y:x*b}),p.push(t))});a=this.qb(c,b);f=this.qb(d,b);return{$c:c,Xc:d,Mc:a,xc:f,Vc:e,zc:k,Sc:m,Nb:p}}qb(a,b=32){var c=r(a.length*b,a.length*b),
d=c.getContext("2d");return ja(a,(e,f,h)=>{var k=e?this.cc(e):null;e&&k&&d.drawImage(k,h*b,f*b)}),c}cc(a){switch(a){case "dirt":return this.Cc;case "grass":return this.Dc;case "water":return this.Jc;case "snow":return this.Gc;case "brick":return this.Bc;case "steel":return this.Hc;case "tree":return this.Ic;case "house":return this.Ec;case "shop":return this.Fc;default:return null}}lc(a=1){var b=this.hc();this.map=b;a*=16;this.O=b=X(b);this.cb=b=this.fc(b,a);this.Qa=this.cb.zc;this.ga=this.cb.Sc;
this.ma=this.cb.Nb;this.sc=L([b.Mc,b.xc])}}class nb{constructor(a,b,c,d,e){this.vb=a;this.h=new q(0,0);this.D=c;this.w=b;this.Db=d;this.Eb=e}Yb(a){this.h=new q(a.x,a.y)}rc(a){this.h=a}move(a){this.h.move(a,32)}Zb(a){var b=this.h.x-this.w/2,c=this.h.y-this.D/2;return W(a,0>b?0:b,0>c?0:c,this.w,this.D)}s(a,b){let c;let d,e,f,h,k,m;var p=this.h.y-this.D/2;c=this.h.x-this.w/2;0>=c&&(c=0,this.h.x=c+this.w/2);0>=p&&(p=0,this.h.y=p+this.D/2);c+this.w>b.width&&(c=b.width-this.w,this.h.x=c+this.w/2);p+this.D>
b.height&&(p=b.height-this.D,this.h.y=p+this.D/2);f=this.Db;h=this.Eb;d=k=this.w;e=m=this.D;a.drawImage(b,c,p,d,e,f,h,k,m)}bc(a,b,c=32){var d=this.h.x-this.w/2,e=this.h.y-this.D/2;a=a+(0>d?0:d)-this.Db;b=b+(0>e?0:e)-this.Eb;return a=Math.floor(a/c)*c,b=Math.floor(b/c)*c,new q(a,b)}}class Ba{constructor(){this.U=6;this.ea=this.da=1;this.fa=10;this.V=this.X=1}Ga(){this.V=this.X=this.fa=this.ea=this.da=this.U=15}static clone(a){var b=new Ba;b.U=a.U;b.da=a.da;b.ea=a.ea;b.fa=a.fa;b.X=a.X;b.V=a.V}Va(a){switch(a){case "ARCHERY":return this.U;
case "HEALTH":return this.da;case "POWER":return this.ea;case "SPEED":return this.fa;case "STELTH":return this.X;case "LUCK":return this.V;default:return 0}}Sb(a,b){switch(a){case "ARCHERY":this.U=b;break;case "HEALTH":this.da=b;break;case "POWER":this.ea=b;break;case "SPEED":this.fa=b;break;case "STELTH":this.X=b;break;case "LUCK":this.V=b}}mc(){return[{n:"HEALTH",za:this.da},{n:"POWER",za:this.ea},{n:"ARCHERY",za:this.U},{n:"SPEED",za:this.fa},{n:"STELTH",za:this.X},{n:"LUCK",za:this.V}]}}class Ca{constructor(a){this.h=
new q(a.x,a.y);this.A=1}s(a){a.drawImage(this.j,this.h.x,this.h.y)}}class O extends Ca{constructor(a){super(a.h);this.e=a;this.direction=a.direction;this.C=this.$();this.j=this.C[this.direction];this.width=this.j.width;this.height=this.j.height;this.speed=this.width;this.Qb=this.e.attributes.U;this.Bb=0;this.A=1}update(a){this.time=a;this.Bb++;this.Bb<this.Qb?(this.h.move(this.direction,this.speed),this.e.Mb(this)):this.A=0}$(){if(O.W)return O.W;var a=this.e.g.M,b=16*a,c=D(g(na,a),b,b);a=R(c,0);b=
R(c,2);var d=R(c,4);c=R(c,6);this.w=a.width;this.D=a.height;return O.W=[c,c,a,a,b,b,d,c],O.W}}class U extends Ca{constructor(a,b,c=1){super(b);this.g=a;this.value=c;this.j=this.$b()}update(a){this.time=a;this.h.I(this.g.i.h)<1.5*this.g.l&&(this.g.i.N+=this.value,this.A=0)}s(a){super.s(a)}$b(){if(U.mb)return U.mb;var a=this.g.l;a=D(g(pa,this.g.M),a,a,!1);return U.mb=a,a}}class ob{constructor(a){this.g=a;this.A=this.ja=100;this.ba=this.Z=this.points=this.N=this.wa=0;this.attributes=new Ba(1);this.h=
new q(0,0);this.destination=new q(0,0);this.Ma=!1;this.time=0;this.direction=4;this.C=this.$();this.j=this.C[4];this.Ha=0;this.xa=[];this.Pa=1E3}Ga(){this.A=this.Pa=this.ba=this.Z=this.points=this.N=1E7;this.attributes.Ga()}wb(){var a=this.g.l*(12-this.attributes.X);return a<=1.5*this.g.l&&(a=1.5*this.g.l),a}setPosition(a){this.h=new q(a.x,a.y);this.destination=new q(a.x,a.y)}update(a){this.Ha=Math.max(this.Ha-1,0);this.xa=this.xa.filter(b=>0<b.A);[...this.xa].forEach(b=>{b.update&&b.update(a)});
this.time=a;0!=this.h.I(this.destination)?(this.Ma=!0,this.h.wc(this.destination,this.j.width/2),this.g.Ea.Yb(this.h)):this.Ma=!1;this.u=this.g.u.filter(b=>b.h.I(this.h)<this.wb());0<this.u.length&&[...this.u].forEach(b=>{b.update&&b.update(this.time)})}Xb(){0<this.Ha||(this.Ha=20-2*this.attributes.U,this.Pa--,this.xa.push(new O(this)),this.yc())}Mb(a){var b=a.h;b=this.g.J.ab(b.x/this.g.l,b.y/this.g.l);1!=b&&1!=b||2==b||(a.A=0);for(let c=0;c<this.g.u.length;c++)b=this.g.u[c],b.h.I(a.h)<this.g.l&&
null!=b.type&&(b.A-=a.A,0>=b.A&&(this.g.u.push(new U(this.g,b.h,b.type+1)),5==b.type?this.wa-=b.type+1:this.wa+=b.type+1),a.A=0)}Xa(){var a=r(this.j.width,3),b=a.getContext("2d");b.fillStyle="green";this.A<this.ja/2&&(b.fillStyle="orange");this.A<this.ja/2&&(b.fillStyle="red");return b.fillRect(0,0,this.A/this.ja*this.j.width,3),a}s(a){a.drawImage(this.j,this.h.x,this.h.y);4==this.direction?a.drawImage(this.R,this.h.x+this.j.width-this.R.width,this.h.y+this.j.height-1.5*this.R.height):6==this.direction?
a.drawImage(ka(this.R),this.h.x+this.j.width-1.6*this.R.width,this.h.y+this.j.height-1.3*this.R.height):2==this.direction&&a.drawImage(this.R,this.h.x+this.j.width-1.2*this.R.width,this.h.y+this.j.height-1.3*this.R.height);[...this.xa].forEach(b=>{b.s&&b.s(a)});a.drawImage(this.Xa(),this.h.x,this.h.y);0<this.Ib&&(a.fillStyle="#ff0000aa",a.fillRect(this.h.x,this.h.y,this.j.width,this.j.height),this.Ib--);this.Rb(a)}ib(a,b){this.direction=a=this.h.Wa(new q(a,b));this.j=this.C[a]}moveTo(a,b){if(!this.g.rb(a,
b)){var c=this.h.Wa(new q(a,b));this.direction=c;0!=this.h.I(new q(a,b))&&(this.j=this.C[c],this.move(c))}}move(a){a===this.direction?this.Ma||this.destination.move(a,this.width):this.direction=a}$(){this.R=g(ma,this.g.M);var a=g(aa,this.g.M),b=g(sa,this.g.M),c=g(ta,this.g.M);return this.width=a.width,this.height=a.height,[b,b,c=D(c,this.width,this.height),a,a,a,ka(c,!0),b]}Ia(){return this.j}yc(){if(this.g.o.ta.la){for(var a=new AudioContext,b=a.createBuffer(1,96E3,48E3),c=b.getChannelData(0),d=
96E3;d--;){var e=d;if(2E4<d)var f=null;else f=(2E4-d)/2E4,f=93&Math.pow(50*d,.7)?f:-f;c[e]=f}c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start()}}Rb(a){var b=this.wb();0>=b||(a.beginPath(),a.arc(this.h.x+this.j.width/2,this.h.y+this.j.width/2,b,0,2*Math.PI,!1),a.setLineDash([5,25]),a.strokeStyle="red",a.stroke(),a.setLineDash([]))}}class pb{constructor(a){this.tc=a;this.rows=a.length;this.cols=a[0].length}ub(a,b,c,d){a=Math.floor(a);b=Math.floor(b);c=Math.floor(c);d=Math.floor(d);
const e=[],f=new Set,h={},k=Array(this.rows).fill(null).map(()=>Array(this.cols).fill(1/0));k[a][b]=0;const m=Array(this.rows).fill(null).map(()=>Array(this.cols).fill(1/0));m[a][b]=this.yb(a,b,c,d);for(e.push([a,b]);0<e.length;){a=this.Vb(e,m);const [p,t]=a;if(p===c&&t===d)return this.Ac(h,a);e.splice(e.indexOf(a),1);f.add(`${p}-${t}`);b=this.ic(p,t);for(const y of b){const [x,C]=y;f.has(`${x}-${C}`)||this.tc[x][C]||(b=k[p][t]+1,b<k[x][C]&&(h[`${x}-${C}`]=a,k[x][C]=b,m[x][C]=b+this.yb(x,C,c,d),e.includes(y)||
e.push(y)))}}return null}yb(a,b,c,d){return Math.abs(a-c)+Math.abs(b-d)}Vb(a,b){let c=a[0],d=b[c[0]][c[1]];for(const e of a){const [f,h]=e;b[f][h]<d&&(c=e,d=b[f][h])}return c}ic(a,b){const c=[];return 0<a&&c.push([a-1,b]),a<this.rows-1&&c.push([a+1,b]),0<b&&c.push([a,b-1]),b<this.cols-1&&c.push([a,b+1]),c}Ac(a,b){const c=[b];for(;a.hasOwnProperty(`${b[0]}-${b[1]}`);)b=a[`${b[0]}-${b[1]}`],c.unshift(b);return c}}class qb extends P{constructor(a){super(a);this.oc()}oc(){this.K=1;this.Ba=5;this.M=2;
this.l=16*this.M;this.keyboard={};this.J=new mb(this,this.M);this.eb=u(this.J.map,.7);this.i=new ob(this);this.o.ta.Sa&&(this.i.N=1E7);this.o.ta.xb&&this.i.Ga();this.i.setPosition(this.J.Qa?this.J.Qa:new q(224,224));this.Ea=new nb(this,this.o.G.width,this.o.G.height,0,0);this.Ea.rc(this.i.h);this.ua="robin hood";this.ga=[...this.J.ga];this.ma=[...this.J.ma];this.u=[];this.hb=this.J.hb;this.Fb=new pb(this.hb);this.Rc=this.Wb();this.tb();this.nb()}Ka(a,b){a=Math.floor(a);b=Math.floor(b);a=new q(a,b);
for(var c=0;c<this.ga.length;c++)if((b=this.ga[c]).h.I(a)<this.l)return b;for(c=0;c<this.u.length;c++)if((b=this.u[c]).h.I(a)<this.l)return b;return null}rb(a,b){return null!=this.Ka(a,b)||this.J.ab(a/this.l,b/this.l)}oa(){var a=r(this.o.G.width,this.o.G.height);let b=a.getContext("2d");b.clearRect(0,0,b.canvas.width,b.canvas.height);b.fillStyle="black";b.fillRect(0,0,b.canvas.width,b.canvas.height);var c=(e=>{if(!e)return null;let f=r(e.width,e.height);return f.getContext("2d").drawImage(e,0,0),
f})(this.J.sc),d=c.getContext("2d");if([...this.u].forEach(e=>{e.s&&e.s(d)}),[...this.ga].forEach(e=>{e.s&&e.s(d)}),[...this.ma].forEach(e=>{e.s&&e.s(d)}),this.i.s(d),this.ca)for(let e in this.ca)b.drawImage(u(this.i.j,.8),this.ca[e][0]*this.l,this.ca[e][1]*this.l);c=this.Ea.Zb(c);return b.drawImage(c,0,0),a}update(a){this.time=a;this.u=this.u.filter(c=>0<c.A);this.i.update(a);for(var b in this.keyboard)this.keyboard[b]&&this.ob(b);if(0>=this.i.A&&(alert("game over"),this.o.B=null,this.i.A=100,this.o.Oa()),
this.ca&&0<this.ca.length)b=this.ca.shift(),this.i.h=new q(b[0]*this.l,b[1]*this.l);0>=this.u.length&&(this.Ba+=5,this.K++,this.nb());[...this.ma].forEach(c=>{c.update&&c.update(a)})}nb(){for(let a=0;a<this.Ba&&!(this.u.length>this.Ba);a++){let b=new E(this,I(0,3));this.u.push(b)}}Wb(){var a=[];for(let c=0;c<this.J.O.length;c++)for(let d=0;d<this.J.O.length;d++){var b=new q(c*this.l,d*this.l);this.J.ab(c,d)||a.push(b)}return a}Ub(){var a=this.tb(8,25);return 0<a.length?a[I(0,a.length)]:new q(this.l,
this.l)}tb(a=8,b=13){var c=this.Rc;c=(c=c.filter(f=>f.I(this.i.h)>this.l*a)).filter(f=>f.I(this.i.h)<this.l*b);var d=[];for(let f in c){var e=!0;for(let h=0;h<this.u.length;h++)if(this.u[h].h.I(new q(c[f].x,c[f].y))<this.l){e=!1;break}e&&d.push(c[f])}return c}pc(){var a=this.i.h.Ab(this.i.direction,this.l);(a=this.Ka(a.x,a.y))&&a.La&&a.La()}ob(a){if(" "!==a&&"space"!==a||this.i.Xb(),"e"===a)this.pc(),this.keyboard={};else if("q"===a)this.keyboard.q=!1,this.o.Oa();else if(!this.i.Ma){var b=this.i.h.clone(),
c=!1;if("s"===a||"ArrowDown"===a?(b.move(4,this.i.height),c=!0):"w"===a||"ArrowUp"===a?(b.move(0,this.i.height),c=!0):"d"===a||"ArrowRight"===a?(b.move(2,this.i.height),c=!0):"a"!==a&&"ArrowLeft"!==a||(b.move(6,this.i.height),c=!0),c)a=this.i.h.Wa(b),this.i.ib(b.x,b.y),a!=this.i.direction?(this.i.ib(b.x,b.y),this.keyboard={}):this.rb(b.x,b.y)?this.i.ib(b.x,b.y):this.i.moveTo(b.x,b.y)}}s(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);
a.fillStyle="green";a.font="16px Arial";a.drawImage(this.oa(),0,0);a.fillStyle="#004b52d6";a.fillRect(0,0,a.canvas.width,48);a.fillStyle="#ffffff";a.fillText("\u2665 "+H(this.i.A),15,15);a.fillText("\u2295 "+H(this.i.wa),15,30);a.fillText("\u263a"+H(this.i.points),15,45);a.fillText("\u27b9\t"+H(this.i.Pa),96,15);a.fillText("\u0556\t"+H(this.i.N),96,30);a.fillText("Mobs "+H(this.u.length),192,15);a.fillText("LVL "+H(this.K),192,30);a.drawImage(Ya,316,4);a.drawImage(Za,316,20);a.fillText("   "+H(this.i.Z),
320,15);a.fillText("   "+H(this.i.ba),320,30);a.drawImage(this.eb,0,a.canvas.height-this.eb.height);q.Ua(a,this.i.h.x/this.l,a.canvas.height-this.eb.height+this.i.h.y/this.l,3,"green")}click(a){var b=this.l;a=this.Ea.bc(a.offsetX,a.offsetY,b);a=new q(a.x,a.y);this.Fb.ub(this.i.h.x/b,this.i.h.y/b,a.x/b,a.y/b)}control(a){this.ob(a)}ra(a){this.keyboard[a.key]=!0}ia(a){this.keyboard[a.key]=!1}}class rb{constructor(a){return this.target=a,this.lb=[],!!a.addEventListener}sub(a){this.lb.push(a)}clear(){this.lb=
[]}fireEvent(a){var b=this.lb,c;for(c in b)b[c].notify&&b[c].notify(a)}}class sb extends P{constructor(a){super(a);this.C={qa:K,i:ya};this.T=400>this.o.G.width?32:100;this.B=this.o.B;this.m=[];this.pb=this.B.i.attributes.mc();for(let b in this.pb)this.m.push({x:this.T,y:192+32*b,k:this.pb[b].n});this.v=0;this.buffer=this.oa()}oa(){var a=r(this.o.G.width,this.o.G.height),b=a.getContext("2d"),c=this.m[0],d=c.x+20;b.drawImage(this.pa("STATISTICS"),d,c.y-64);b.drawImage(this.pa("POINTS"),d,c.y-32);for(let e in this.m)c=
this.m[e],b.drawImage(this.pa(`${c.k} `),d,c.y);return a}update(a){this.time=a}pa(a){return A.get(a,24,"white",this.C.qa)}s(a){a.clearRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="black";a.fillRect(0,0,a.canvas.width,a.canvas.height);a.fillStyle="green";a.font="16px Arial";var b=this.m[0],c=b.x+20;a.drawImage(this.buffer,0,0);a.drawImage(this.pa(`${this.B.i.points}`),c+150,b.y-32);for(let d in this.m)b=this.m[d],a.drawImage(this.pa(`${this.B.i.attributes.Va(b.k)}`),c+150,b.y);a.drawImage(this.C.i,
this.m[this.v].x,this.m[this.v].y+4);a.fillText("Time "+this.time,20,20)}click(){}control(a){if("q"===a)this.o.Oa();else if("w"===a||"ArrowUp"===a)0==this.v?this.v=this.m.length-1:this.v=Q(this.v-1)%this.m.length;else if("s"===a||"ArrowDown"===a)this.v=Q(this.v+1)%this.m.length;else if("d"==a||"ArrowRight"==a){if(0>=this.B.i.points)return void alert("no points to use");this.v;a=this.m[this.v].k;10<=this.B.i.attributes.Va(a)?alert("level max reached"):confirm("spend points on upgrading skill "+a)&&
(this.B.i.attributes.Sb(a,this.B.i.attributes.Va(a)+1),--this.B.i.points)}}ra(){}ia(a){this.control(a.key)}}class tb{constructor(a){this.G=a;this.Fa=document.querySelector(a.Fa);this.canvas=Object.assign(document.createElement("canvas"),{width:a.width,height:a.height,className:"gamecanvas"});this.Fa.appendChild(this.canvas);this.H=new rb(document);["keydown","keyup"].forEach(b=>{document.addEventListener(b,c=>{this.H.fireEvent({name:b,event:c})})});this.canvas.addEventListener("click",b=>{this.H.fireEvent({name:"click",
event:b})});this.Oc();400>this.G.width&&(a.framerate/=2);this.Ra=new Ga(a.framerate,this,!0);this.Tb()}update(a){if(0==this.Ra.p)if(this.time=a,this.g)try{this.g.update(a),this.g.s(this.canvas.getContext("2d"))}catch(b){console.log(b),this.Ra.stop()}else this.Ra.stop()}Oc(){this.g=new fb(this);this.H.clear();this.H.sub(this.g)}Oa(){this.ta||(this.ta=new hb(this));this.g=this.ta;this.H.clear();this.H.sub(this.g)}Nc(){this.B||(this.B=new qb(this));this.g=this.B;this.H.clear();this.H.sub(this.g)}Pc(){this.Kb||
(this.Kb=new sb(this));this.g=this.Kb;this.H.clear();this.H.sub(this.g)}Tb(){if(!(400<this.G.width)){var a=Object.assign(document.createElement("div"),{className:"controls_container"});a.innerHTML="<table>\n        <tr><td id='q'>q</td><td id='w'>w</td><td id='e'>e</td><td class=\"padding\"></td><td id='space'>space</td> </tr>\n        <tr><td id='a'>a</td><td id='s'>s</td><td id='d'>d</td><td class=\"padding\"></td><td id='f'>f</td></tr></table>";this.Fa.appendChild(a);var b=((c,d=document)=>d.querySelectorAll(c))(".controls_container td");
for(let c=0;c<b.length;c++)b[c].addEventListener("click",()=>{this.H.fireEvent({name:"control",event:{key:b[c].id}})}),b[c].addEventListener("touchstart",()=>{this.H.fireEvent({name:"controlts",event:{key:b[c].id}})}),b[c].addEventListener("touchend",()=>{this.H.fireEvent({name:"controlte",event:{key:b[c].id}})})}}}const ub={Fa:".canvas_container",Zc:32,Tc:1,framerate:1/30,width:32*parseInt(window.innerWidth/32),height:32*parseInt(window.innerHeight/32),Uc:"Assets",Yc:ia("#spriteSheetMain")};class vb extends tb{constructor(a){super(a)}}
document.addEventListener("DOMContentLoaded",function(){window.vb||(window.vb=new vb(ub))},!1)})();
